### ISSUE TITLE
请问可以让输出字体加粗吗

### ISSUE THREAD

**Issue by xizhing8069** [yihong0618/bilingual_book_maker#104]
请问可以让输出字体加粗吗
谢谢

**Comment by yihong0618** [comment]
理论可以，但这个我觉得自己 DIY 比较好。

**Comment by xizhing8069** [comment]
感谢回复，我也想入手自己改一下但是不知道怎么入手，问了gpt说要改css？请教一下，多谢

**Comment by yihong0618** [comment]
是的，改 html 或 css 都行，本质上 epub 是一大堆 html

**Comment by xizhing8069** [comment]
不好意思具体问一下改哪个文件呢？感谢

**Comment by hleft** [comment]
`--translation_style` 可以自己配置翻译部分样式了
