### ISSUE TITLE
输出和书相同的英文

### ISSUE THREAD

**Issue by rogerfedererforever** [yihong0618/bilingual_book_maker#113]
请问一下 python3 make_book.py --book_name test_books/Savingtime.epub --model gpt3 --no_limit --language "Simplified Chinese 输出和书相同的英文，没有翻译为中文，是什么原因？
![微信截图_20230308185924](https://user-images.githubusercontent.com/104702947/223696707-80ce0da9-2cac-4438-97f2-560ecba47df0.png)

**Comment by yihong0618** [comment]
--language "Simplified Chinese 这个去掉试试
可能有 bug 我稍后改下

**Comment by yihong0618** [comment]
我这边试了下没问题。。。

**Comment by rogerfedererforever** [comment]
还是不行也，我去掉了语言设置，py make_book.py --book_name test_books/animalfarm.epub --model gpt3 --no_limit 请问还需要设置哪嘛？
![image](https://user-images.githubusercontent.com/104702947/223700969-11f6fcb4-2af9-4c81-83a7-d688a9a1ba31.png)

**Comment by hleft** [comment]
有过按ctrl-c 然后出现重复相同的翻译后的结果，但你是重复没翻译的结果（我没用过--model和--no_limit)

**Comment by Brikarl** [comment]
> 有过按ctrl-c 然后出现重复相同的翻译后的结果，但你是重复没翻译的结果（我没用过--model和--no_limit)

https://github.com/yihong0618/bilingual_book_maker/pull/124 最新的提交应该已经修复了。
