### ISSUE TITLE
Request: Concurrently completing a book

### ISSUE THREAD

**Issue by hleft** [yihong0618/bilingual_book_maker#116]
I was wondering if anyone is doing or wants to do this feature for concurrent translation using multiple api_keys, if someone is doing it, great, very useful. 

If it doesn't need to be improved to consider various concurrent state error cases (server errors, own network errors, ctrl+c), without considering good concurrency practices, and completing the most basic functionality can be merged, I can try to pr it , otherwise I'll wait for someone else to complete it.

**Comment by yihong0618** [comment]
1. multiple api_key its support multiple keys concurrent not. The current implementations all have a little problem.

PR welcome but FYI #62 did some work
