### ISSUE TITLE
94%位置中断后不能恢复

### ISSUE THREAD

**Issue by DeeWooo** [yihong0618/bilingual_book_maker#120]
怎么重来都不行
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/7700516/223884178-2351ce5f-f7e7-4e12-b6e1-6a38bd86371e.png">

**Comment by yihong0618** [comment]
还生成了个 temp 文件，你看看那个？

**Comment by DeeWooo** [comment]
> 

晕，temp里面是全的？这是什么原因？

**Comment by yihong0618** [comment]
temp 是你在中断时候自动传一份，你中断时候几乎翻译完了。。。所以是全的
