### ISSUE TITLE
翻译到这里停止，这种是什么错误, 怎么修复

### ISSUE THREAD

**Issue by bluesyk** [yihong0618/bilingual_book_maker#121]
Detect the use of a vulnerable kubectl instance: kubectl versions 1.12.9, 
1.13.6, and 1.14.2 have a fix for this issue. The use of any versions earlier 
than this will trigger the following rule:

检测使用易受攻击的kubectl实例：kubectl 
1.12.9、1.13.6和1.14.2版本已修复此问题。使用早于此版本的任何版本将触发以下规则
：
- macro: safe_kubectl_version

宏：safe_kubectl_version
**closing tag '[/userAgent]' at position 24 doesn't match any open tag**
you can resume it next time
17630it [8:25:35,  1.72s/it]
Process finished with exit code 0

---------------------------------------------测试书籍-----------------------

Learn Kubernetes Security
Copyright © 2020 Packt Publishing

第十三章 Chapter 13: Learning from Kubernetes CVEs
...
Detect the use of a vulnerable kubectl instance: kubectl versions 1.12.9, 1.13.6, and 1.14.2 have a fix for this issue. The use of any versions earlier than this will trigger the following rule:

- macro: safe_kubectl_version

  condition: (jevt.value[**/userAgent**] startswith "kubectl/v1.15" or

              jevt.value[/userAgent] startswith "kubectl/v1.14.3" or

              jevt.value[/userAgent

**Comment by bluesyk** [comment]
昨天做个翻译测试，今天马上被停止服务了.
-- | --
 
Hi there,After a thorough investigation, we have determined that you or a member of your organization are using the OpenAI API in ways that violate our policies.Due to this breach we are halting access to the API immediately for the organization Personal. Common reasons for breach include violations of our content policy, repeated attempts at disallowed use-cases, or accessing the API from an unsupported location. You may also wish to review our Terms of Use. If you believe this is in error and would like to appeal, please contact us through our help center. We will review appeals within one business day and will contact you if we reinstate access to the API. 
Best
The OpenAI team

**Comment by yihong0618** [comment]
被停止服务是因为 proxy....
