### ISSUE TITLE
这算是竞品吗😂

### ISSUE THREAD

**Issue by Brikarl** [yihong0618/bilingual_book_maker#122]
https://fsys.app/

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/28230530/223901436-3854d00a-36bf-40b1-a301-f06a160ca467.png">

**Comment by yihong0618** [comment]
哈哈哈哈，正常。

**Comment by yihong0618** [comment]
看到推了，不过本身就是 MIT 协议，从任何角度讲都没问题，这个 Issue 先关了哈～

**Comment by hleft** [comment]
~~五分钟极速翻译~~ 300页的epub, 17元 63分钟
