### ISSUE TITLE
希望可以支持多个openai  key，轮询获取信息

### ISSUE THREAD

**Issue by levie-vans** [yihong0618/bilingual_book_maker#13]
OpenAI信用卡太难绑定了，如果可以支持多个key轮询，就可以解决限速和数量的问题。
key列表写进配置文件里。

**Comment by yihong0618** [comment]
issue 里有朋友在做，你可以翻一下

**Comment by guaguaguaxia** [comment]
https://github.com/yihong0618/bilingual_book_maker/pull/14

**Comment by yihong0618** [comment]
Done
