### ISSUE TITLE
未翻译成功

### ISSUE THREAD

**Issue by OneTe** [yihong0618/bilingual_book_maker#130]
执行后python3.8 [make_book.py](http://make_book.py/) --book_name test_books/The_Alchemist.epub --openai_key xxxxx --language zh-hans直接就结束了，生成了一本未翻译的版本，这个是什么问题呢？

/usr/local/lib/python3.8/site-packages/ebooklib/epub.py:1395: UserWarning: In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')
0it [00:00, ?it/s]

**Comment by yihong0618** [comment]
可能是这个原因
https://github.com/yihong0618/bilingual_book_maker/pull/126
你用 test book 先试验一下？没问题看看书是不是里面没有段落或者段落全是 div
然后参考 readme 翻译 div 标签

**Comment by OneTe** [comment]
> 

真是全是div，修改后可以翻译了，感谢哈🙏。提个建议发现有div可以给个提示哈😄

**Comment by yihong0618** [comment]
我想想怎么设计下

**Comment by yihong0618** [comment]
我在 readme 里加上指向这个 issue 吧

**Comment by chleeab** [comment]
可不可以加個if loop
如果翻譯在2秒內完成，便提醒user 可能有這個Issue

**Comment by yihong0618** [comment]
可以我研究下

FarmerL ***@***.***> 于2023年3月10日周五 17:10写道：
