### ISSUE TITLE
希望添加专业术语字典

### ISSUE THREAD

**Issue by sealevelsun** [yihong0618/bilingual_book_maker#132]
今天翻译一本长篇小说，发现翻译后的小说的人名前后不统一。
如果增加一个可选参数，txt文件？可以人为指定一些原文词汇对应的翻译，然后在逐段提交翻译时带上这个字典，或许可以解决这种名字前后不统一的问题

**Comment by sealevelsun** [comment]
一个临时解决建议。
加个可选配置，这个配置的作用是每次提交原文给gpt，都带上一句咒语：段落中的人名不翻译，保持原文。

**Comment by hleft** [comment]
我改了几个prompt让它别翻译人名，但它还是坚持翻译

**Comment by yihong0618** [comment]
I think its done
