### ISSUE TITLE
请教作者如何能翻译提速

### ISSUE THREAD

**Issue by GOWxx** [yihong0618/bilingual_book_maker#134]
首先，感谢作者的贡献，谢谢！

我添加的 api key 是付费的 api，rate limit 还是比较高的
想问有没有什么办法可以提高翻译速度？现在是一句一句翻译的，比较慢，40k个翻译块，程序跑了半天了翻译了15k个块。
请问有没有可能增加同时有多个请求在发送的模式？
最好能给提供参数，给并行数或单位时间内总数设限

**Comment by hleft** [comment]
https://github.com/yihong0618/bilingual_book_maker/pull/62

**Comment by yihong0618** [comment]
@GOWxx 使用 #62 的 fork 因为我这边测试还有一点点问题，所以还没来的及合并
周末会看一下。

**Comment by GOWxx** [comment]
> 

收到，感谢回复，感谢贡献！

**Comment by GOWxx** [comment]
> 

收到，感谢回复。
看了下似乎还不能保证稳定运行，但我愿意使用它，能跑通比较好，不能的话也可以反馈下问题。

**Comment by yihong0618** [comment]
@GOWxx 谢谢

**Comment by hleft** [comment]
我也pr了一个 不过不能resume, 处理错误

**Comment by GOWxx** [comment]
用 #62 的更改代码合并到了 main 分支的 [代码](https://github.com/GOWxx/bilingual_book_maker/tree/test_batch_processing) 实测
开启 `--batch_size=50` ，大约 2.5 小时翻译完“哈利波特”七部，纯英文版 148 万左右的单词，近 4 万内容块
作为对比，昨晚用没加 `--batch_size`参数的 bilingual_book_maker 大概跑了 10 个小时才 1/3 的样子

现在 #62 的问题可能跨平台兼容性不太行，macos 上能跑，centos 8.6 上跑不了。

**Comment by yihong0618** [comment]
@GOWxx 感谢测试，现在问题是，我们需要想办法要用户尽可能的 work 然后再考虑效率。。。

**Comment by GOWxx** [comment]
时间太久，暂时关闭了。
