### ISSUE TITLE
bug: Translated p tags with only images

### ISSUE THREAD

**Issue by hleft** [yihong0618/bilingual_book_maker#140]
![compare](https://user-images.githubusercontent.com/89069008/224326424-d1a6f827-69aa-4f2e-8e9c-c66ea9ce716f.png)

![compare2](https://user-images.githubusercontent.com/89069008/224327328-b2c7232c-27dd-4b06-b81d-0d7a886c17a7.png)

should skip

**Comment by yihong0618** [comment]
seems we have ignore this ....no text..
can you offer me a sample ?

**Comment by hleft** [comment]
@yihong0618 you mean a  file.epub?

**Comment by yihong0618** [comment]
sorry I think its ok
can you open a pr fix it？

**Comment by hleft** [comment]
@yihong0618  If no one else does it, I may do it.. But I hope that others can finish it directly if they are familiar with it

**Comment by yihong0618** [comment]
OK thanks a lot as always!

**Comment by hleft** [comment]
sorry this cause by myself, https://github.com/yihong0618/bilingual_book_maker/pull/136, fixed
