### ISSUE TITLE
 module 'openai' has no attribute 'ChatCompletion' will sleep 60 seconds

### ISSUE THREAD

**Issue by jjustwin** [yihong0618/bilingual_book_maker#165]
Hi，
there is a mistake after execute :
python3 make_book.py --book_name test_books/the_little_prince.txt --openai_key xxxxxx  --test --language zh-hans

**Comment by yihong0618** [comment]
pip3 install -U openai

**Comment by yihong0618** [comment]
@taohuajianxian 目前 overload 了。。。官方模型 limit.
![image](https://user-images.githubusercontent.com/15976103/225624411-d88eaf5b-2ad6-4090-8f19-033763331d72.png)

**Comment by taohuajianxian** [comment]
> 你可以使用 --model gpt3

成功了，感谢大佬！
