### ISSUE TITLE
bug: lost css in generated epub

### ISSUE THREAD

**Issue by hleft** [yihong0618/bilingual_book_maker#173]
Even the example in test_books is the same. I unzip the generated epub and find that the `<head>` in html is missing.

I tried to find the reason but couldn't...

**Comment by yihong0618** [comment]
do not use --allow_navigable_strings

**Comment by hleft** [comment]
@yihong0618  I did not use this option

**Comment by yihong0618** [comment]
after your pr merge css lost？

**Comment by hleft** [comment]
@yihong0618  It should have existed a long time ago, so the books in test_books/ have this problem

**Comment by hleft** [comment]
@yihong0618 
```
from ebooklib import epub


def main():
    input_epub_path = "input.epub"
    output_epub_path = "output.epub"

    book = epub.read_epub(input_epub_path)
    epub.write_epub(output_epub_path, book)


if __name__ == "__main__":
    main()
```

I try this will cause lose `<head>`

**Comment by yihong0618** [comment]
its ok for now, let us try to figure out why~

**Comment by hleft** [comment]
@yihong0618  It can be solved by modifying one line of code in ebooklib, but the original repo has not been updated for several months. How about copying its code and referencing the local library after modification?  On the right is the modified

![compare](https://user-images.githubusercontent.com/89069008/225838223-bc910f63-5ab1-4124-9555-76a623c8299a.png)

**Comment by yihong0618** [comment]
we can use money patch

**Comment by yihong0618** [comment]
like what I did 
you can try or you can share which line I will try to fix it
https://github.com/yihong0618/bilingual_book_maker/blob/main/book_maker/loader/epub_loader.py#L144-L164

**Comment by hleft** [comment]
@yihong0618  https://github.com/aerkalov/ebooklib/blob/a55089afc40042e2dcaddd2fc7364192f0b3ca0a/ebooklib/epub.py#L1360
change to `self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), item.content)` will work

**Comment by yihong0618** [comment]
@hleft seems not ebooklib's bug....let me check
