### ISSUE TITLE
tiktoken 安装失败

### ISSUE THREAD

**Issue by zfy68** [yihong0618/bilingual_book_maker#178]
请教下这个包如何安装，我试了几种方式都不行

`  from book_maker.loader.epub_loader import EPUBBookLoader
  File "H:\GitHub_Stu_Py\bilingual_book_maker\book_maker\loader\epub_loader.py", line 4, in <module>
    import tiktoken
ModuleNotFoundError: No module named 'tiktoken'`

**Comment by yihong0618** [comment]
pip install -U tiktoken

**Comment by zfy68** [comment]
> 



> pip install -U tiktoken

已成功，谢谢啦

**Comment by yihong0618** [comment]
enen

**Comment by FLSY-XYW** [comment]
请教一下，tiktoken在python3.11.3环境下安装失败
Failed to build tiktoken
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects
但是我下载好pyproject.toml仍然不行
![image](https://user-images.githubusercontent.com/90819847/236661788-066763ea-dd8d-4599-8fde-753faa42d781.png)
