### ISSUE TITLE
Does DeepL API Free work

### ISSUE THREAD

**Issue by Royhowtohack** [yihong0618/bilingual_book_maker#179]
![IMG_1962](https://user-images.githubusercontent.com/52094557/225803572-b02aa988-d7d2-4128-93ce-2c4ad27fbfa0.JPG)

**Comment by yihong0618** [comment]
Not sure, will test this weekend

**Comment by Royhowtohack** [comment]
Both **google** and **openai** work for me, but not deepl free API. I haven't been able to solve the problem. 

<img width="755" alt="Screen Shot 2023-03-18 at 10 11 43 PM" src="https://user-images.githubusercontent.com/52094557/226111424-b12a3ee0-1b1a-4785-8e27-c60018823258.png">

**Comment by yihong0618** [comment]
deepl free api do not support for now
check the deepl readme link

**Comment by Royhowtohack** [comment]
problem solved, Thanks!

**Comment by abdurahmanadilovic** [comment]
how did you solve the issue @Royhowtohack? I want to try to use deepl free version
