### ISSUE TITLE
没有报错，但也没有翻译过的新文件生成

### ISSUE THREAD

**Issue by yangyuwen-bri** [yihong0618/bilingual_book_maker#182]
利用animal_farm这本书做翻译测试是成功的，生成了翻译好的新的文件；但我再换其他两本的时候就没有新文件生成了，代码肯定是没问题，请问大家有这种情况吗？
python3 make_book.py make_book.py --book_name test_books/lemo.epub --openai_key ${***}  --test --language zh-hans
换lemo这本就不行，好怪 = =

**Comment by yihong0618** [comment]
我试试

**Comment by yihong0618** [comment]
可能有 bug…我昨晚改东西了，晚上我看看

**Comment by yihong0618** [comment]
@y
测了下没问题，生成的在 test_books 里。test_books/lemo_bilingual.epub

**Comment by yihong0618** [comment]
lemo 刚刚测试可以
试去掉 --test --language zh-hans
