### ISSUE TITLE
成功翻译后的.EPUB 为原文

### ISSUE THREAD

**Issue by soanhee** [yihong0618/bilingual_book_maker#183]
- 使用 GPT3.0 (FREE) 翻译
- 尝试过test_book 和自己的epub
- 尝试过TEST 和 完整翻译
- 运行都100% 完成没有任何错误
- 繁体简体都尝试过

结果都是显示原文(新生成的 epub 所有内容都复制了一遍)，请问是需要付费版的API才能成功翻译吗?
感恩

**Comment by yihong0618** [comment]
@soanhee 用的是 git 么？

**Comment by yihong0618** [comment]
不需要付费版 api 
最快的方式是用 --model google 试试

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/226091904-e06db79f-a40d-4dfb-9de3-e3524b3eeed6.png)

我这边刚刚测试没有问题，你可以拉一下最新代码

**Comment by soanhee** [comment]
> 不需要付费版 api 最快的方式是用 --model google 试试

十分感谢，Google成功翻译了，但GPT 3.0不行，是 BUG 还是什么原因呢?
或者有哪些方法可以DEBUG?

**Comment by yihong0618** [comment]
不用加 —model gpt3 直接用默认的

**Comment by yihong0618** [comment]
或者你有运行的截图么，可以发到这里

**Comment by soanhee** [comment]
> 不用加 —model gpt3 直接用默认的

默认的翻译20条后就会显示配额已满，**以下是使用gpt3运行的截图**:

`(base) Y:\_Github\Bilingual_Book_Maker\bilingual_book_maker>python make_book.py --book_name books/oahspe2.epub --model gpt3 --translate-tags h1,h2,h3,p,div,a,b --openai_key ${*****************} --language zh-hant --test
C:\Users\sohee\anaconda3\lib\site-packages\ebooklib\epub.py:1395: UserWarning: In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')
  0%|                                                                                           | 0/10 [00:00<?, ?it/s]OAHSPE
 10%|████████▎                                                                          | 1/10 [00:02<00:24,  2.68s/it]A KOSMON BIBLE IN THE WORDS OF JEHOVIH AND HIS ANGEL EMBASSADORS
 30%|████████████████████████▉                                                          | 3/10 [00:03<00:06,  1.05it/s]BY
 50%|█████████████████████████████████████████▌                                         | 5/10 [00:06<00:06,  1.26s/it]JOHN BALLOU NEWBROUGH
 70%|██████████████████████████████████████████████████████████                         | 7/10 [00:07<00:02,  1.01it/s]Oahspe by John Ballou Newbrough.
23it [00:07,  5.49it/s]                                                                                                This edition was created and published by Global Grey
©GlobalGrey 2018
26it [00:19,  1.19it/s]globalgreyebooks.com
28it [00:28,  1.39s/it]globalgreyebooks.com
Contents
30it [00:28,  1.19s/it]A General Statement Of The Contents Of Oahspe
31it [00:32,  1.03s/it]`




**这是GOOGLE成功的纪录:**

`(base) Y:\_Github\Bilingual_Book_Maker\bilingual_book_maker>python make_book.py --book_name books/oahspe2.epub --model google --translate-tags h1,h2,h3,p,div,a,b --openai_key ${******************} --language zh-hant --test
C:\Users\sohee\anaconda3\lib\site-packages\ebooklib\epub.py:1395: UserWarning: In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')
  0%|                                                                                           | 0/10 [00:00<?, ?it/s]OAHSPE
OAHSPE
 10%|████████▎                                                                          | 1/10 [00:00<00:00,  9.34it/s]A KOSMON BIBLE IN THE WORDS OF JEHOVIH AND HIS ANGEL EMBASSADORS
耶和华和他的天使使者所说的科斯蒙圣经
 30%|████████████████████████▉                                                          | 3/10 [00:00<00:00, 14.99it/s]BY
经过
JOHN BALLOU NEWBROUGH
约翰·巴卢·纽布劳
Oahspe by John Ballou Newbrough.
John Ballou Newbrough 的 Oahspe。
23it [00:00, 65.51it/s]                                                                                                This edition was created and published by Global Grey
此版本由 Global Gray 创建和发布
©GlobalGrey 2018
©GlobalGrey 2018
globalgreyebooks.com
globalgreyebooks.com
globalgreyebooks.com
globalgreyebooks.com
29it [00:00, 44.09it/s]Contents
内容
A General Statement Of The Contents Of Oahspe
Oahspe 内容的一般说明
31it [00:02, 12.81it/s]`

**Comment by yihong0618** [comment]
继续等啊，是触发 limit 了 代码里有 sleep 或者用多个 token

**Comment by soanhee** [comment]
> 

尝试了几个免费版的API都反馈
"Incorrect API key provided: ${sk-BUW******************************************TCw}. You can find your API key at https://platform.openai.com/account/api-keys. will sleep 60 seconds"

**Comment by yihong0618** [comment]
这几个 key 用不了

**Comment by soanhee** [comment]
> 这几个 key 用不了

默认model必需使用 3.5的key?

**Comment by yihong0618** [comment]
不是。。。用 默认的必须 3.5 的key --model gpt3 是 gpt3 的 key
但无论哪个 key 都得保证可用

**Comment by yangyuwen-bri** [comment]
> 不是。。。用 默认的必须 3.5 的key --model gpt3 是 gpt3 的 key 但无论哪个 key 都得保证可用

我用Latin Vulgate这本书测试了，结果是没问题的，跑出来的文件翻译完整。但我自己另找的一本书就存在我说的那个问题了T-T 明明在终端100%翻译完了，生成的文件却只有扉页简介翻译了

**Comment by soanhee** [comment]
> 继续等啊，是触发 limit 了 代码里有 sleep 或者用多个 token

感谢🙏🏻不加gpt3成功运行了，请问用多个token要怎么实现呢？说明中找不到

**Comment by soanhee** [comment]
> 不是。。。用 默认的必须 3.5 的key --model gpt3 是 gpt3 的 key
> 但无论哪个 key 都得保证可用

感谢🙏🏻不加gpt3成功运行了，如果运行了一半暂停了，突然想加多个token一齐翻译要怎么实现呢？

**Comment by soanhee** [comment]
> 不是。。。用 默认的必须 3.5 的key --model gpt3 是 gpt3 的 key 但无论哪个 key 都得保证可用

感谢🙏🏻不加gpt3成功运行了
