### ISSUE TITLE
这种二级的缩紧的没有翻译 有什么解决思路吗 或者提供思路我来解决

### ISSUE THREAD

**Issue by DaviRain-Su** [yihong0618/bilingual_book_maker#19]
<img width="587" alt="截屏2023-03-04 11 09 12" src="https://user-images.githubusercontent.com/53282030/222872909-883486be-83c3-4be4-987c-18cf38c3eefe.png">

**Comment by yihong0618** [comment]
不难解决的，现在只翻译了 p 源码里你能找到主食，在那地方改就行，支持 2 级的

**Comment by yihong0618** [comment]
@DaviRain-Su 有兴趣 PR welcome

**Comment by DaviRain-Su** [comment]
> @DaviRain-Su 有兴趣 PR welcome

哎 python不太行 改不动了

**Comment by yihong0618** [comment]
I think its done
