### ISSUE TITLE
Hope you can add additional judgement to the <p> tags within the table.

### ISSUE THREAD

**Issue by adolphnov** [yihong0618/bilingual_book_maker#191]
First of all, I really appreciate your effort on developing this project.
However, I have a small request to make and I hope you could take a look.

I have a book with tables that contain `<p>` tags, and when running the code of this project, some symbols in these `<p>` tags are also being translated. I am not sure which part of the code can add a logic of "not translating `<p>` tags in tables". I would greatly appreciate it if you could add such logic to the project or guide me on how to modify the code accordingly.

Here are some examples:

<img width="867" alt="image" src="https://user-images.githubusercontent.com/30210690/226162005-e564ee31-280e-4a06-beb6-5f869578e06d.png">

Translated results:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/30210690/226162077-63a711ec-9afa-442f-873a-1d62e1dba19e.png">

I hope that an optional parameter can be added to disable table translation.

**Comment by yihong0618** [comment]
thanks will make a try

**Comment by hleft** [comment]
https://github.com/yihong0618/bilingual_book_maker/blob/e0aef6f8afda7bbab85d7d3d1930a4110ae1e852/book_maker/loader/epub_loader.py#L137

when using `--accumulated_num`, the translation of the sup label is excluded. Add an option allow the configuration to look more reasonable

**Comment by yihong0618** [comment]
@hleft thanks

**Comment by adolphnov** [comment]
You guys replied so fast! Thank you very much for trying to improve this.

**Comment by hleft** [comment]
This didn't solve why it was close.. I also encountered this problem today and wanted to add an option exclusion tag

**Comment by yihong0618** [comment]
sorry for that reopen it now
