### ISSUE TITLE
Incorrect API key，API测试可用

### ISSUE THREAD

**Issue by yangyuwen-bri** [yihong0618/bilingual_book_maker#195]
Incorrect API key provided: ${sk-0rF******************************************1pS}.
但我测试过API是可用的，也换了几次网络（直接对话Chat GPT没问题），我是免费用户（但看之前的issues说免费应该也是支持的？），请问这可能是什么原因呢？

**Comment by yihong0618** [comment]
可能是今天 openai 服务问题， 也可能是 key 不可用
请用 repl 环境实验一下

**Comment by laysite** [comment]
> 我遇到了同样的问题：
> Incorrect API key provided: D57rV0ys************************************Pp9p. You can find your API key at https://platform.openai.com/account/api-keys. will sleep 60 seconds


我解决了，需要删除外面的括号。--openai_key "sk-D57rVxxxxx'' ，而不需要包含任何括号.

**Comment by drummangas** [comment]
> > 我遇到了同样的问题：
> > Incorrect API key provided: D57rV0ys************************************Pp9p. You can find your API key at https://platform.openai.com/account/api-keys. will sleep 60 seconds
> 
> 我解决了，需要删除外面的括号。--openai_key "sk-D57rVxxxxx'' ，而不需要包含任何括号.

Muchas gracias! Funcionó perfectamente.
