### ISSUE TITLE
不知道为什么行首行末会自动加了双引号

### ISSUE THREAD

**Issue by Otiguy** [yihong0618/bilingual_book_maker#199]
版本：#193 

![image](https://user-images.githubusercontent.com/48633984/226852998-3c1f348c-d3e5-4969-9774-0f5cbefee7ce.png)

不知道为什么行首行末会自动加了双引号

我的指令是：
`python3 make_book.py --book_name test_books/Dialoguetext.txt --openai_key ${openai_key} --test --language "English" --batch_size 1`

**Comment by hleft** [comment]
不知道了, txt部分没看过.. 可以txt内容截图多发点，方便别人看双引号都在哪

**Comment by Otiguy** [comment]
> 不知道了, txt部分没看过.. 可以txt内容截图多发点，方便别人看双引号都在哪

![image](https://user-images.githubusercontent.com/48633984/226982568-c4740adf-b087-454f-9308-3d49fa335715.png)

**Comment by Otiguy** [comment]
[Dialogue.txt](https://github.com/yihong0618/bilingual_book_maker/files/11080155/Dialogue.txt)



> 看起来像是原文中就有“” 可以提供下原文吗

**Comment by zstone12** [comment]
@Otiguy  
![image](https://user-images.githubusercontent.com/28105615/227988413-c86b5668-9ee7-479a-af9b-8fa2c7695705.png)
我这里使用彩云小译没用办法复现这个问题

**Comment by Otiguy** [comment]
我用的是GPT

> @Otiguy ![image](https://user-images.githubusercontent.com/28105615/227988413-c86b5668-9ee7-479a-af9b-8fa2c7695705.png) 我这里使用彩云小译没用办法复现这个问题

**Comment by zstone12** [comment]
> 我用的是GPT
> 
> > @Otiguy ![image](https://user-images.githubusercontent.com/28105615/227988413-c86b5668-9ee7-479a-af9b-8fa2c7695705.png) 我这里使用彩云小译没用办法复现这个问题

get.过些时候会对尝试验证下GPT的情况，你可以尝试下其他模型比如chataccount，如果对翻译要求没有那么高的话，彩云小译以及其他 model 理论上可以也可以进行使用。

**Comment by zstone12** [comment]
@Otiguy 用默认的chatgpt 模型我这边也复现了这个问题。可以通过带上参数 '--prompt prompt_template_sample.txt'，替换下prompt 的用词，我这边看来是可以解决这个问题的。

**Comment by Otiguy** [comment]
@zstone12 

```
python3 make_book.py --book_name test_books/Dialogue.txt --openai_key ${openai_key} --prompt prompt_template_sample.json --language "en" --batch_size 1
```
```
{
  "system": "You are a translation engine that can only translate text and cannot interpret it.",
  "user": "Translate the given text to {language}. Be faithful or accurate in translation. Make the translation readable or intelligible. Be elegant or natural in translation. If the text cannot be translated, return the original text as is. Do not translate person's name. Do not add any additional text in the translation. Do not change the capitalization of the original text. The text to be translated is: \n{text}"
}
```



> @Otiguy 用默认的chatgpt 模型我这边也复现了这个问题，猜测是GPT理解这些语句为对话，所以自动加上了“”。可以通过带上参数 '--prompt prompt_template_sample.txt'，替换下prompt 的用词，我这边看来是可以解决这个问题的。

**Comment by zstone12** [comment]
> python3 make_book.py --book_name test_books/Dialogue.txt --openai_key ${openai_key} --prompt prompt_t

用json 这种方式可以OK的，可以看下是否解决问题了

**Comment by Otiguy** [comment]
> > python3 make_book.py --book_name test_books/Dialogue.txt --openai_key ${openai_key} --prompt prompt_t
> 
> 用json 这种方式可以OK的，可以看下是否解决问题了

我就是这样设定的，还是有引号

**Comment by zstone12** [comment]
@Otiguy 可以再试试直接在promot 中告诉gpt 不要使用引号。
![image](https://user-images.githubusercontent.com/28105615/228287247-318a042a-8e64-48a4-b1ba-720907bf4ce9.png)

**Comment by yihong0618** [comment]
@zstone12 thanks
