### ISSUE TITLE
可以加参数指定翻译具体的章节吗？

### ISSUE THREAD

**Issue by asasas234** [yihong0618/bilingual_book_maker#210]
有些书我不想翻译整本，只想翻译我感兴趣的章节，这样速度会快一些，也可以省钱，这个功能可以支持一下吗？

**Comment by zstone12** [comment]
目前可能采取的方式可以是手动中断翻译。又或者看下是否有拆分equb书章节的其他工具。

**Comment by hleft** [comment]
https://github.com/yihong0618/bilingual_book_maker/blob/1e7c8f9ce41aaf6f97f3f760b2f859a55d9830d2/book_maker/loader/epub_loader.py#L388

我经常打开这里注释只翻译epub中某个文件

**Comment by yihong0618** [comment]
@hleft thanks
