### ISSUE TITLE
epub翻译部分后自动停止 ('In the future version we will turn default option ignore_ncx to True.')

### ISSUE THREAD

**Issue by 39Hz** [yihong0618/bilingual_book_maker#211]
提示信息:
In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')
epub文件只有开头一小部分被翻译,尝试翻译中添加-- option但没有找到对应选项,请问该如何解决?

**Comment by zstone12** [comment]
In the future version we will turn default option ignore_ncx to True.
warnings.warn('In the future version we will turn default option ignore_ncx to True.') 这个提示信息可以忽略，不会对结果产生影响。可以给出执行的命令，以及对应的书籍吗

**Comment by 39Hz** [comment]
你好，我不知道该怎么在issue中添加附件，所以把使用的命令、环境，翻译的epub原件和输出文件全部传到[这里](https://github.com/39Hz/issue_of_book)了

**Comment by zstone12** [comment]
@hleft @yihong0618 看起来确实是存在一些问题，有时间可以看下
![image](https://user-images.githubusercontent.com/28105615/228278113-b7b77060-a23d-4e55-b76a-3ab15301aee0.png)

**Comment by yihong0618** [comment]
好的，我这两天看一下

**Comment by ciceroxiao** [comment]
个人也遇到过这种情况，我换个节点就能顺利运行。

**Comment by 39Hz** [comment]
> 个人也遇到过这种情况，我换个节点就能顺利运行。

但是在相同节点情况下，我更换了别的epub文件，可以正常完成翻译工作。

**Comment by Zacharia2** [comment]
`book = epub.read_epub(epubfile, {"ignore_ncx": True})` 

加上这个选项就不会出现警告了。但忽略造成的效果不知道是啥。

**Comment by yihong0618** [comment]
> ```python
> book = epub.read_epub(epubfile, {"ignore_ncx": True})
> ```
> 
> 加上这个选项就不会出现警告了。但忽略造成的效果不知道是啥。

我之后加一下，谢谢
