### ISSUE TITLE
请问使用 plus 账户有封禁风险吗?

### ISSUE THREAD

**Issue by MikeKen-Ken** [yihong0618/bilingual_book_maker#217]
plus 看起来更快一些? 请问会有封禁账号的风险吗? 非常感谢.

**Comment by hleft** [comment]
不清楚 但我默认会有 所以还不敢用...

**Comment by MikeKen-Ken** [comment]
> 不清楚 但我默认会有 所以还不敢用...

是啊..感觉挺玄乎的, 我的 plus 目前用了一周还挺正常. 不太敢用这个来测试...

**Comment by yihong0618** [comment]
一直都有。。。但目前情况来看 plus 风险稍微低点儿

**Comment by yihong0618** [comment]
可以试试这个
https://github.com/acheong08/ChatGPT-Proxy-V4

**Comment by yihong0618** [comment]
研究了一下 Drop 掉了，不想让大家承担这个风险。
