### ISSUE TITLE
Contents in the list were not translated

### ISSUE THREAD

**Issue by woyin** [yihong0618/bilingual_book_maker#218]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/35319250/229057086-5dce7d37-cd75-45cc-84a3-45f4afb2344d.png">
I've updated the app to the latest version, but all contents in lists were not translated.

**Comment by hleft** [comment]
Are you translating epub? By default, only `<p>` of epub is translated. If you want to translate more tags, you can refer to `--translate-tags "p,li,h1,h2,h3,h4,h5,h6,blockquote,div"`

**Comment by woyin** [comment]
> Are you translating epub? By default, only `<p>` of epub is translated. If you want to translate more tags, you can refer to `--translate-tags "p,li,h1,h2,h3,h4,h5,h6,blockquote,div"`

Thanks for your reply. When I run the command with `--translate-tags "p,li,h1,h2,h3,h4,h5,h6,blockquote,div"`, all the contents were translated.
