### ISSUE TITLE
可否幫譯文上色？

### ISSUE THREAD

**Issue by doggy8088** [yihong0618/bilingual_book_maker#222]
目前翻譯過程中，原文與譯文都是白色，建議「譯文」部分可以上點顏色作區分，如下圖示：

![image](https://user-images.githubusercontent.com/88981/229323761-07499a02-0e8d-4e8d-ac89-725bd534e350.png)

但我目前找不到輸出的地方，不知道可否提示我譯文輸出在畫面上的代碼是在哪一行？

上色的語法如下：

```py
print(f"\033[32m{t_text}\033[0m")
```

**Comment by kj-huang** [comment]
可以在輸出行加入 span，因為程式有  beautiful soup

**Comment by yihong0618** [comment]
@doggy8088 类似在这里

https://github.com/yihong0618/bilingual_book_maker/blob/main/book_maker/translator/chatgptapi_translator.py#L134

**Comment by yihong0618** [comment]
@doggy8088 项目依赖里有 rich

https://rich.readthedocs.io/en/stable/markup.html?highlight=print#syntax
可以这样

```python
from rich import print
print("[bold red]alert![/bold red] Something happened")
```
