### ISSUE TITLE
ModuleNotFoundError   from revChatGPT.V1 import Chatbot

### ISSUE THREAD

**Issue by yaoshihyu2023** [yihong0618/bilingual_book_maker#225]
In [1]: from revChatGPT.V1 import Chatbot
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-23bd15626201> in <module>
----> 1 from revChatGPT.V1 import Chatbot

from revChatGPT.ChatGPT import Chatbot

**Comment by yihong0618** [comment]
pip install -U revChatGPT
