### ISSUE TITLE
PUID is required

### ISSUE THREAD

**Issue by love520sakura** [yihong0618/bilingual_book_maker#230]
请问一下，使用chatgptaccount model，却出现PUID is required?
明明已经订阅ChatGPT Plus了......

**Comment by yihong0618** [comment]
@love520sakura 
请参考https://github.com/acheong08/ChatGPT

**Comment by love520sakura** [comment]
@yihong0618 感謝您，已成功解決

**Comment by love520sakura** [comment]
@yihong0618 感谢您，已成功解决

**Comment by DevinFu** [comment]
> @yihong0618 感谢您，已成功解决

你好，我也遇到这个问题了，请问是怎么解决的？

**Comment by DevinFu** [comment]
> @DevinFu book_maker\translator\chatgpt_account_translator.py -> ChatGPTAccount -> translate，里面有使用Chatbot，config中增加你的session_token和paid设为True就可以了。 `chatbot = Chatbot( config={ "email": self.chatgpt_account, "password": self.chatgpt_password, "access_token": "<access_token>", "paid": True } )` 另外session_token从这边拿：[https://chat.openai.com/api/auth/session。](https://chat.openai.com/api/auth/session%E3%80%82)

```
        chatbot = Chatbot(
            config={
                "email": self.chatgpt_account,
                "password": self.chatgpt_password,
                "session_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJhamNrZnhAeWluaGVseC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJ1c2VyX2lkIjoidXNlci1QT0VNQTVuT29BdkdlS1NvT045YjFIWEgifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDY0MWE4MzRlOGU5MWU4M2I4ODkyMmE0MSIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2ODA1MTE0NTgsImV4cCI6MTY4MTcyMTA1OCwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvZmZsaW5lX2FjY2VzcyJ9.NIkSkO3T0O9cZAsfCTy5VbaUdB0LGVEPVCinZ26XkGS3h3Z2Bf-OUKjMZE_rhXDBMtVMP0jrHFbdz1IrAY8w2mrP5Ytw3n088WuaDVQ1KSuVHvOq-eOe67izGw1qdq9i5uSG_NfkoblwIXKyIYicMwkaUG5Bs_dWKkB0w1Av3-uOc8OlsWp0ccJ1oPHcqfkZ7LowCDrlggtFPsq-gH5xkPt2K1lg3mMEz_YRnkF02yaffnNXy6OuaqG43uMlW51uLj27HGGRzB0oCdtCQ_l6XPE8KBzRxweHm-s1-mLvvifwL2j8-3YQczpCTTUwpnRyZjMoEJCGIVQNIFzzqT6kOg",
                "access_token": "7C0038b2a2494c658adac5db3fc23c98386ef0a80dafb313d2169d82a40a2342ad",
                "paid": True
            }
        )
```
我用的是这种形式，报错invalid access token. session_token是按你说的方式拿到的，应该没错，access_token是在cookies里拿的csrf-token字段，不知道是不是对的，你遇到过类似问题吗？

**Comment by yihong0618** [comment]
@DevinFu 我的建议是别在任何场合暴露你的 token .

**Comment by DevinFu** [comment]
@yihong0618 抱歉，目的是方便重现问题，token是临时的，完了log out一下就失效了

**Comment by love520sakura** [comment]
@DevinFu 
不要暴露accessToken，这个好像是不变的？
依我来看你session_token的值看起来像access_token的，你试著把eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZC.....改成access_token，另外不要放上session_token

**Comment by DevinFu** [comment]
还是不行，一样的报错信息，如果你那边可以的话，那貌似是revChatGPT的问题了，最近它有改动了。
