### ISSUE TITLE
[Feature Request 提案] 是否有機會增加 Markdown File (.md) Translate

### ISSUE THREAD

**Issue by androchentw** [yihong0618/bilingual_book_maker#232]
---
* name: Feature request
* about: Suggest an idea for this project
* title: '[Feature Request 提案] 是否有機會增加 Markdown Translate'
* labels: enhancement
---

## 狀況描述

1. 目前我在使用 Hugo 進行 Blog 撰寫，並試圖做 i18n。文章主體都是 *.md，標頭會包含一些 yaml，內容可能包含部分 html code。
2. 雖然想過 markdown -> epub -> translate -> epub -> markdown，但可能環境沒設定好，一直得不到想要的結果。

還沒詳細研究 code，想請問是否有實作的方向建議，也許有其他大大或我也可以來研究一下怎麼將此功能加入?

或是已經有哪些 GitHub repo 已經在進行類似的事了呢？感謝!

**Comment by wizardforcel** [comment]
openai的训练文本就是markdown，直接塞给他就可以了。
