### ISSUE TITLE
在amazon购买的书转成epub后翻译到一半卡主，报错 'NoneType' object has no attribute 'encode' will sleep 30 seconds

### ISSUE THREAD

**Issue by qingwenlyu** [yihong0618/bilingual_book_maker#239]
使用calibre把azw3转成epub，刚开始翻译是ok的，但是在42%的地方卡住了，重试也无效。报错句如下，辛苦帮助看下。
“Because out of all of humanity, you are the only person that Trisolaris wants dead.”
'NoneType' object has no attribute 'encode' will sleep 30 seconds
 42%|███████████████████████████████████▋                                                  | 2083/5016 [00:20<00:00, 4310.30it/s]'NoneType' object has no attribute 'encode' will sleep 30 seconds

**Comment by runes780** [comment]
same question here

**Comment by qingwenlyu** [comment]
重试了，已修复。谢谢
