### ISSUE TITLE
请对DeepL API Free的支持！

### ISSUE THREAD

**Issue by sagehere** [yihong0618/bilingual_book_maker#245]
DeepL API Free的 API域名为：api-free.deepl.com，与现有的‘deepl_translator.py'中的API接口不一致，导致无法翻译。
谢谢！

**Comment by Royhowtohack** [comment]
I also need this!

**Comment by sagehere** [comment]
自己解决了，修改了deepl_translator.py。
首先需要安装deepl官方支持库deepl
import json
import time
import deepl
import requests
import re

from book_maker.utils import LANGUAGES, TO_LANGUAGE_CODE

from .base_translator import Base
from rich import print


class DeepL(Base):
    """
    caiyun translator
    """

    def __init__(self, key, language, **kwargs) -> None:
        super().__init__(key, language)
        l = None
        l = language if language in LANGUAGES else TO_LANGUAGE_CODE.get(language)
        if l not in [
            "bg",
            "zh",
            "cs",
            "da",
            "nl",
            "en-US",
            "en-GB",
            "et",
            "fi",
            "fr",
            "de",
            "el",
            "hu",
            "id",
            "it",
            "ja",
            "lv",
            "lt",
            "pl",
            "pt-PT",
            "pt-BR",
            "ro",
            "ru",
            "sk",
            "sl",
            "es",
            "sv",
            "tr",
            "uk",
            "ko",
            "nb",
        ]:
            raise Exception(f"DeepL do not support {l}")
        self.language = l

    def rotate_key(self):
        pass
    

    def translate(self, text):
        self.rotate_key()
        translator = deepl.Translator(f"{next(self.keys)}")
        print(text)
        try:
            result = translator.translate_text(text, target_lang=self.language)
        except Exception as e:
            print(e)
            time.sleep(30)
            result = translator.translate_text(text, target_lang=self.language)


        t_text = result.text
        print("[bold green]" + re.sub("\n{3,}", "\n\n", t_text) + "[/bold green]")
        return t_text

**Comment by yihong0618** [comment]
@sagehere 谢谢，但这个不会有 limit 限制么？

**Comment by Royhowtohack** [comment]
> @yihong0618 自己解决了，修改了deepl_translator.py。 首先需要安装deepl官方支持库deepl 该库支持free 与pro 只要填入key即可。
> 
> 修改后的代码: import json import time import deepl import requests import re
> 
> from book_maker.utils import LANGUAGES, TO_LANGUAGE_CODE
> 
> from .base_translator import Base from rich import print
> 
> class DeepL(Base): """ caiyun translator """
> 
> ```
> def __init__(self, key, language, **kwargs) -> None:
>     super().__init__(key, language)
>     l = None
>     l = language if language in LANGUAGES else TO_LANGUAGE_CODE.get(language)
>     if l not in [
>         "bg",
>         "zh",
>         "cs",
>         "da",
>         "nl",
>         "en-US",
>         "en-GB",
>         "et",
>         "fi",
>         "fr",
>         "de",
>         "el",
>         "hu",
>         "id",
>         "it",
>         "ja",
>         "lv",
>         "lt",
>         "pl",
>         "pt-PT",
>         "pt-BR",
>         "ro",
>         "ru",
>         "sk",
>         "sl",
>         "es",
>         "sv",
>         "tr",
>         "uk",
>         "ko",
>         "nb",
>     ]:
>         raise Exception(f"DeepL do not support {l}")
>     self.language = l
> 
> def rotate_key(self):
>     pass
> 
> 
> def translate(self, text):
>     self.rotate_key()
>     translator = deepl.Translator(f"{next(self.keys)}")
>     print(text)
>     try:
>         result = translator.translate_text(text, target_lang=self.language)
>     except Exception as e:
>         print(e)
>         time.sleep(30)
>         result = translator.translate_text(text, target_lang=self.language)
> 
> 
>     t_text = result.text
>     print("[bold green]" + re.sub("\n{3,}", "\n\n", t_text) + "[/bold green]")
>     return t_text
> ```

非常感谢：
我遇到以下报错
```
1
First you go to our website
Unexpected request failure: 'latin-1' codec can't encode character '\u2018' in position 
15: ordinal not in range(256)
```

**Comment by yihong0618** [comment]
Done
