### ISSUE TITLE
如何进行后台翻译

### ISSUE THREAD

**Issue by xingwozhonghua** [yihong0618/bilingual_book_maker#248]
因为墙问题我在本地的机器即使开全局代理，并配置代理端口，程序依然无法访问open ai的接口，我就使用阿里云的香港服务器，
我用ssh连接上香港服务器进程翻译，可以访问open ai的接口，但是只有我把链接终端关闭，它翻译后台的进程就不见了，所以希望可以添加一个后台翻译的功能，这样我可以关闭链接终端。等个半天再到服务器查看是否翻译完毕。

**Comment by yihong0618** [comment]
```
nohup python3 ..... &

ps aux | grep python3
```

**Comment by xingwozhonghua** [comment]
谢谢，可以了
