### ISSUE TITLE
[CI] Recommendation: add pytest-vcr into tests

### ISSUE THREAD

**Issue by YYLIZH** [yihong0618/bilingual_book_maker#258]
# Description
Current tests will consume your api quota every time when a PR is merged. A test with vcr will intercept the new http request and replay a recorded one. This may safe your api quota.

Pros:
1. Safe api quota and speed up tests.
2. Still can run when openai server is down.

Cons:
1. May not be aware of api change. (seldom happen)

# Reference
https://pytest-vcr.readthedocs.io/en/latest/

**Comment by yihong0618** [comment]
we do not have `Unit testing` so We should keep real world  test maybe better.
About the cost  I think its OK for just `main` branch merge
