### ISSUE TITLE
内容审查，跳跃

### ISSUE THREAD

**Issue by williamswang23** [yihong0618/bilingual_book_maker#261]
采用的azure的服务。
在英文书的部分内容出发了azure的内容审查，导致翻译过程中止并提前结束。
如果可以，希望能加入跳过部分小节，或者 从制定的小节开始翻译的功能（以此人工跳过敏感部分）。
谢谢

**Comment by yihong0618** [comment]
我们之后看一下，我觉得这种内容用 DeepL 更稳定一点？

**Comment by joostshao** [comment]
思路+建议：可以先用没审查的来翻译，然后再~

**Comment by williamswang23** [comment]
> 我们之后看一下，我觉得这种内容用 DeepL 更稳定一点？

了解，谢谢。

**Comment by williamswang23** [comment]
> 思路+建议：可以先用没审查的来翻译，然后再~

感谢建议。
