### ISSUE TITLE
README.md & README-CN.md 内容错误

### ISSUE THREAD

**Issue by Kevin-Eric** [yihong0618/bilingual_book_maker#268]
![image](https://user-images.githubusercontent.com/13802207/236359041-9db0e99c-655d-45d0-ab37-81d4b15ed0e2.png)

此处应为`BBM_OPENAI_API_KEY`

![image](https://user-images.githubusercontent.com/13802207/236359092-946361fc-bef0-4477-a394-3e0f503414d0.png)

**Comment by yihong0618** [comment]
Thanks fixed
