### ISSUE TITLE
TXT翻譯使用--batch_size會有喪失排版的問題

### ISSUE THREAD

**Issue by myforself** [yihong0618/bilingual_book_maker#269]
當使用使用--batch_size 10以上時，翻譯後文本所有字都堆在一起了…

另順便問一下，對DEEPL的免費API更新了嗎？

**Comment by yihong0618** [comment]
1. @zstone12 我们看一下
2. 还没

**Comment by zstone12** [comment]
@myforself 我这边尝试了没有发现什么异常。可以给一下运行截图和执行命令吗

**Comment by myforself** [comment]
> @myforself 我这边尝试了没有发现什么异常。可以给一下运行截图和执行命令吗

我的API餘額已經用光…
至於執行命令是python make_book.py --book_name test_books/cof.txt --openai_key (KEY用光了) --language zh-hans --batch_size 30

![image](https://user-images.githubusercontent.com/30555797/236738021-138eb03e-ec6c-48ea-b03b-2508d1ce2772.png)

**Comment by zstone12** [comment]
> > @myforself 我这边尝试了没有发现什么异常。可以给一下运行截图和执行命令吗
> 
> 我的API餘額已經用光…正在苦等各位大佬把免費的 DEEPL API弄出來 至於執行命令是python make_book.py --book_name test_books/cof.txt --openai_key (KEY用光了) --language zh-hans --batch_size 30 圖片如下︰ ![image](https://user-images.githubusercontent.com/30555797/236738021-138eb03e-ec6c-48ea-b03b-2508d1ce2772.png)
> 
> 所有句子直接合在一起了…明明原來都有排好版的。

排版问题在目前没有太好的办法,batch_size就是将几段话进行了合并，如果想要保持原有的排版，只能是batch_size=1

**Comment by myforself** [comment]
> > > @myforself 我这边尝试了没有发现什么异常。可以给一下运行截图和执行命令吗
> > 
> > 
> > 我的API餘額已經用光…正在苦等各位大佬把免費的 DEEPL API弄出來 至於執行命令是python make_book.py --book_name test_books/cof.txt --openai_key (KEY用光了) --language zh-hans --batch_size 30 圖片如下︰ ![image](https://user-images.githubusercontent.com/30555797/236738021-138eb03e-ec6c-48ea-b03b-2508d1ce2772.png)
> > 所有句子直接合在一起了…明明原來都有排好版的。
> 
> 排版问题在目前没有太好的办法,batch_size就是将几段话进行了合并，如果想要保持原有的排版，只能是batch_size=1

但有時倒是非常偶然的正常發揮正常排版…我想會不會是AI回傳時候出問題？如果要求AI排版可行嗎？

**Comment by WeeAris** [comment]
@yihong0618 我怀疑这个排版的问题是由于在读取文本文件时使用了`f.read.split("\n")`，把原文中的换行符删掉了导致的，我建议换成`f.readlines()`来保留符号。

**Comment by tudoujunha** [comment]
@yihong0618 拉代码使用发现还是有丧失排版的问题，排查了一段时间，原因找到了：
https://github.com/yihong0618/bilingual_book_maker/blob/6c0f1e3b95397c535059f814223136acdbcbdcba/book_maker/loader/txt_loader.py#L70

这里 batch_text = "".join(i) 需要 换成 batch_text = "\n".join(i)

"".join(i) 直接操作不会保留换行符，显示成这样：
![屏幕截图 2023-07-30 043214](https://github.com/yihong0618/bilingual_book_maker/assets/131859738/cf46636f-34d0-4e20-88cd-0f90ccae2969)

"\n".join(i) 修改后测试OK:
![屏幕截图 2023-07-30 043308](https://github.com/yihong0618/bilingual_book_maker/assets/131859738/ced23f99-f5ce-4bf7-bdfd-fd934a3d60f7)

**Comment by myforself** [comment]
> @yihong0618 拉代码使用发现还是有丧失排版的问题，排查了一段时间，原因找到了：
> 
> https://github.com/yihong0618/bilingual_book_maker/blob/6c0f1e3b95397c535059f814223136acdbcbdcba/book_maker/loader/txt_loader.py#L70
> 
> 这里 batch_text = "".join(i) 需要 换成 batch_text = "\n".join(i)
> 
> "".join(i) 直接操作不会保留换行符，显示成这样： ![屏幕截图 2023-07-30 043214](https://user-images.githubusercontent.com/131859738/257009599-cf46636f-34d0-4e20-88cd-0f90ccae2969.jpg)
> 
> "\n".join(i) 修改后测试OK: ![屏幕截图 2023-07-30 043308](https://user-images.githubusercontent.com/131859738/257009625-ced23f99-f5ce-4bf7-bdfd-fd934a3d60f7.jpg)

大佬牛逼，期待更新

**Comment by yihong0618** [comment]
@tudoujunha 感恩，我更新下

**Comment by yihong0618** [comment]
更新了感谢 @tudoujunha @myforself

**Comment by myforself** [comment]
> 更新了感谢 @tudoujunha @myforself

@yihong0618 

![image](https://github.com/yihong0618/bilingual_book_maker/assets/30555797/a46b428d-39bb-4f84-af93-b9a0d83ef328)

指令為python make_book.py --book_name test_books/spray.txt --model google --language zh-hans --batch_size 20 

問題仍然沒有修復:(
原檔案是有格式的︰
![image](https://github.com/yihong0618/bilingual_book_maker/assets/30555797/560094fc-8b7b-4f3f-ba84-01aab1fd99b7)
