### ISSUE TITLE
why gtp4 is not work?

### ISSUE THREAD

**Issue by lucieYang** [yihong0618/bilingual_book_maker#298]
The model: `gpt-4` does not exist will shows.
But my CHATGTP plus is avaliable to use

**Comment by xiaolai** [comment]
here said "gpt4 doesnot exist".
gpt3 works well.

**Comment by yihong0618** [comment]
Will check it, thanks.

**Comment by easm002** [comment]
is it fixed?

**Comment by myforself** [comment]
> Will check it, thanks.

所以是不是死症了 :(

**Comment by yihong0618** [comment]
> > Will check it, thanks.
> 
> 所以是不是死症了 :(

还没有 gpt4 api..m

**Comment by myforself** [comment]
> 

最近我見GPT4好像能買了，你要不要看看。
不過只要活著就好…我還已經這裡已被放棄了，畢竟最後一次更新都是6月的事

**Comment by yihong0618** [comment]
> 最近我見GPT4好像能買了，你要不要看看。
> 不過只要活著就好…我還已經這裡已被放棄了，畢竟最後一次更新都是6月的事

精力在其它项目上，抱歉。issue 和维护还是做的

**Comment by myforself** [comment]
> > 最近我見GPT4好像能買了，你要不要看看。
> > 不過只要活著就好…我還已經這裡已被放棄了，畢竟最後一次更新都是6月的事
> 
> 精力在其它项目上，抱歉。issue 和维护还是做的

別這樣說，我作為伸手黨就是想知道還會不會繼續更，餘下就是等待嘛
老大加油

**Comment by myforself** [comment]
> > 最近我見GPT4好像能買了，你要不要看看。
> > 不過只要活著就好…我還已經這裡已被放棄了，畢竟最後一次更新都是6月的事
> 
> 精力在其它项目上，抱歉。issue 和维护还是做的

問一下，現在是不是GPT3.5 turbo默認？
如果不是，指令是甚麼？

有點等不及GPT4修復了…打算先沖一點點API再說…

**Comment by yihong0618** [comment]
@myforself 

gpt4 没问题。。。。

try  python3 make_book.py --model gpt4 --book_name test_books/lemo.epub

**Comment by myforself** [comment]
> @myforself @xiaolai @easm002
> 
> gpt4 没问题。。。。
> 
> try python3 make_book.py --model gpt4 --book_name test_books/lemo.epub

指令為︰python make_book.py --book_name/wild.txt --model gpt4 --openai_key XXX --language zh-hant --batch_size 20

![image](https://github.com/yihong0618/bilingual_book_maker/assets/30555797/0a760a47-05fd-40ce-bc98-32e965e6df93)

試了回來無法運行，是不是我問題？

**Comment by myforself** [comment]
![image](https://github.com/yihong0618/bilingual_book_maker/assets/30555797/9bae0947-1909-4dd8-9316-8d087f4ad08f)


-h 顯示沒有GPT4

**Comment by yihong0618** [comment]
git pull 用最新的代码

**Comment by myforself** [comment]
> git pull 用最新的代码

![image](https://github.com/yihong0618/bilingual_book_maker/assets/30555797/529622d2-1c12-4b8b-8bff-7eed3f00ba8a)


變這樣了

**Comment by yihong0618** [comment]
pip install -r requirements.txt

**Comment by myforself** [comment]
> pip install -r requirements.txt

好像能行，正在跑了。看來是我的版本問題，我明明都UPDATE了啊…

**Comment by yihong0618** [comment]
不客气。。。GPT4 太贵了。。。

**Comment by myforself** [comment]
> 不客气。。。GPT4 太贵了。。。

確實…GPT3.5-turbo他們出了個優化版，要不要搞搞看？

============================================

都不知道為什麼發生這個問題，明明其他都能用…難受，想哭。麻煩到老大了

**Comment by myforself** [comment]
> > 不客气。。。GPT4 太贵了。。。
> 
> 確實…GPT3.5-turbo他們出了個優化版，要不要搞搞看MODEL？
> 
> ============================================
> 
> 都不知道為什麼發生這個問題，明明其他都能用…難受，想哭。麻煩到老大了

**Comment by yihong0618** [comment]
> 

有精力的我看一下
