### ISSUE TITLE
网络不稳定的问题

### ISSUE THREAD

**Issue by ed4win** [yihong0618/bilingual_book_maker#3]
翻译一本书的时间比较长，遇到网络不稳定的，等待60秒后直接断开，翻译到一半的内容就没了。提个建议，在翻译过程中定期暂存一下？

**Comment by yihong0618** [comment]
TODO

**Comment by yihong0618** [comment]
@ed4win 之后会加这个，我想想办法哈，但应该不是这几天了，如果你有兴趣可以提 PR

**Comment by yihong0618** [comment]
支持了。
