### ISSUE TITLE
运行命令报错，python3 make_book.py --book_name test_books2/2022_A_Review_of_Indirect_Time-of-Flight_Technologies.epub --openai_key sk-xxxxxxxxxxxxx --language zh-hans

### ISSUE THREAD

**Issue by MysTer1ous** [yihong0618/bilingual_book_maker#300]
![image](https://github.com/yihong0618/bilingual_book_maker/assets/28255159/41112e3b-e19e-49a6-b6c5-ddddcbf55592)
报错如上图

**Comment by yihong0618** [comment]
我门看一下。看起来不是报错了，是文件没解析成功。
你参考 README 翻译 div 试试

**Comment by MysTer1ous** [comment]
> 我门看一下。看起来不是报错了，是文件没解析成功。 你参考 README 翻译 div 试试

好的，我先去试试，先谢谢大佬

**Comment by yihong0618** [comment]
不客气，刚才你截图有 key, 我直接删掉了抱歉。

**Comment by MysTer1ous** [comment]
> 不客气，刚才你截图有 key, 我直接删掉了抱歉。

没事的，谢谢大佬删除及时，不过我运行python3 make_book.py --book_name test_books2/2022_A_Review_of_Indirect_Time-of-Flight_Technologies.epub --openai_key sk-xxxxxxxxxxx --translate-tags div,p会有报错，而且报错好像跟刚才的内容是一样的
![image](https://github.com/yihong0618/bilingual_book_maker/assets/28255159/91a449e0-7668-4ed6-9c05-fa2bda298f9e)

**Comment by yihong0618** [comment]
你翻译里面的 test_book 试试，看看能正常跑不

**Comment by MysTer1ous** [comment]
我翻译了test_book 的lemo.epub为中文是正常的,
![image](https://github.com/yihong0618/bilingual_book_maker/assets/28255159/46bd8032-a076-4ac2-b34e-39816239c153)
只是api的请求限制了速度，那这么说是我自己的epub电子书文件有问题吧？另外请问下哪个文件能改模型

**Comment by yihong0618** [comment]
@MysTer1ous 是的，书可能有问题，你可以把标签都放上试试。

**Comment by MysTer1ous** [comment]
lemo.epub翻译完成后显示
![image](https://github.com/yihong0618/bilingual_book_maker/assets/28255159/e4c1f6ed-0d95-484b-be83-169dc06d9d8a)
请问这个应该不影响翻译后的电子书是么？我把标签都放上是指：python3 make_book.py --book_name test_books2/2022_A_Review.epub --openai_key sk-xxxxxxxxxxx --translate-tags div,p --language zh-hans   这样子写命令么
