### ISSUE TITLE
标题没有翻译，不知道出啥问题了

### ISSUE THREAD

**Issue by wizardforcel** [yihong0618/bilingual_book_maker#309]
![image](https://github.com/yihong0618/bilingual_book_maker/assets/5080126/95c8aed4-43d4-4205-9876-dacd99fdd53b)

**Comment by yihong0618** [comment]
@wizardforcel 
有实验这个么

> epub 由 html 文件组成。默认情况下，我们只翻译 <p> 中的内容。 使用 --translate-tags 指定需要翻译的标签。使用逗号分隔多个标签。例如： --translate-tags h1,h2,h3,p,div

**Comment by wizardforcel** [comment]
@yihong0618 建议把`h1, h2, h3, p, li, blockquote`设为默认

**Comment by yihong0618** [comment]
@wizardforcel 谢谢，我研究下
