### ISSUE TITLE
建议支持自定义数据源翻译 比如txt

### ISSUE THREAD

**Issue by cumany** [yihong0618/bilingual_book_maker#32]
建议支持自定义数据源翻译 比如txt，甚至网页。 如果内容太长可以自动分割提交

**Comment by DennySORA** [comment]
目前已經正在規劃，感謝提出意見。

可以看看目前 txt 加入的這個：#35

**Comment by yihong0618** [comment]
txt Done 
Thanks @DennySORA and @zstone12
