### ISSUE TITLE
txt文件只能限制翻译10行吗？我想翻译整个文件怎么操作，有几行就--batch_size 几？

### ISSUE THREAD

**Issue by shxiq01** [yihong0618/bilingual_book_maker#329]
txt文件只能限制翻译10行吗？我想翻译整个文件怎么操作，有几行就--batch_size 几？

**Comment by yihong0618** [comment]
不是，能正常翻译完，可以试试 --model google

**Comment by shxiq01** [comment]
> 不是，能正常翻译完，可以试试 --model google

`python3 make_book.py --book_name /Users/shixiaoqi/Downloads/hehe.txt --language "English" --single_translate --model gpt3 --openai_key ****`

大佬看一下我这没问题吧？试了两次都只输出了开头10行的英文，剩下的都是原文

**Comment by shxiq01** [comment]
> 
<img width="1416" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/12861435/af28eeef-18ba-46e7-b683-ff0c28681177">


感谢大佬，纠正一下，不是开头10行，好像是开头20行，貌似翻译了两个批次，就不再进行了

**Comment by yihong0618** [comment]
--model google  用这个 model 试试不用 gpt3

**Comment by yihong0618** [comment]
啊哈，我看看，可能是 gpt3 的问题，你用 chatgpt 或者其他的 model 试试

**Comment by shxiq01** [comment]
> 啊哈，我看看，可能是 gpt3 的问题，你用 chatgpt 或者其他的 model 试试


大佬，去掉model参数，用默认的GPT3.5是可以的，应该是gpt3的问题

**Comment by yihong0618** [comment]
gpt3  我这边也没问题。
