### ISSUE TITLE
两种语言段落交叉展示

### ISSUE THREAD

**Issue by lindeer** [yihong0618/bilingual_book_maker#33]
一个展示效果的问题。
一般书籍的段落都很长，但人的眼睛范围差不多是语句长度的。如果翻译段落和原文段落分开，看了一段翻译想找到原文或者再从原文回到翻译，会经常发生眼睛原文语句和翻译语句衔接不上的问题，这个问题有点难受，因此希望实现成如下的效果：
![](https://i.stack.imgur.com/SLsnm.jpg)
有没有前端大佬解决这个痛点或者提供个思路？

**Comment by DennySORA** [comment]
能在更詳細的說明嗎？

**Comment by lindeer** [comment]
@DennySORA 希望译文不要另起一段，直接穿插在原文段落中，这样非常方便读者进行原文和译文的对照，我附了一张效果图，还有哪些我没有说清的点呢？

**Comment by DennySORA** [comment]
瞭解了，我在思考思考，感謝。

**Comment by lindeer** [comment]
@DennySORA 我找到[一个解决办法](https://stackoverflow.com/a/75651428/1265973)，不过有点瑕疵
