### ISSUE TITLE
Is it possible to ask the parser to split the text when submitting to translate?

### ISSUE THREAD

**Issue by simongcc** [yihong0618/bilingual_book_maker#333]
Hello! There are some text inside the epub regarded as too long like:

This model's maximum context length is 4096 tokens. However, your messages resulted in 8648 tokens. 
Please reduce the length of the messages.

Is it possible to instruct the maker to split the text when it encounter long text?

**Comment by yihong0618** [comment]
will change the default to 16k

**Comment by yihong0618** [comment]
Done
