### ISSUE TITLE
-- resume 好像有点问题？翻译整书的时候，当token不够用的情况下，会怎么样，能断点续翻吗？

### ISSUE THREAD

**Issue by shxiq01** [yihong0618/bilingual_book_maker#339]
假设token不够用，导致翻译中断，那充值以后，还能继续从上次的位置开始接着翻吗？如果可以的话，需要怎么做呢？

**Comment by shxiq01** [comment]
-- resume 好像有点问题？我在--single_translate的情况下，翻译过程中手动中断，然后加入-- resume，翻译结果是双语的。

**Comment by yihong0618** [comment]
可能是个 bug...我们看下

**Comment by shxiq01** [comment]
> 可能是个 bug...我们看下

好像只要ctrl c中断，--single_translate就不生效了，麻烦老板验证一下

**Comment by yihong0618** [comment]
@shxiq01 --resume 时候也要加上 --single_translate

**Comment by yihong0618** [comment]
刚测试了，如果有问题随时打开哈
