### ISSUE TITLE
希望增加 <code> 标签代码注释功能 

### ISSUE THREAD

**Issue by zangwill** [yihong0618/bilingual_book_maker#349]
很多编程书里面的代码使用 `<code>` 标签放代码，希望增加如果遇到 code 标签，则自动添加注释和文档功能。

**Comment by yihong0618** [comment]
这个目前有些困难，因为可能无法确定哪些是代码哪些是注释，可能需要 prompt 来辅助（这样就只有 ChatGPT 才行）我们需要考虑下怎么做

**Comment by myforself** [comment]
> 这个目前有些困难，因为可能无法确定哪些是代码哪些是注释，可能需要 prompt 来辅助（这样就只有 ChatGPT 才行）我们需要考虑下怎么做

一個多月沒更新我還以為被放棄了…感恩還在…
順便借地問一下，有關翻譯出現格式錯誤的問題是不是目前還沒有進展…？
我最近發現的問題是「"」引號符經常會在翻譯過程中被刪掉，所以回報一下有沒有可能是與引號有關

**Comment by yihong0618** [comment]
> > 这个目前有些困难，因为可能无法确定哪些是代码哪些是注释，可能需要 prompt 来辅助（这样就只有 ChatGPT 才行）我们需要考虑下怎么做
> 
> 一個多月沒更新我還以為被放棄了…感恩還在… 順便借地問一下，有關翻譯出現格式錯誤的問題是不是目前還沒有進展…？ 我最近發現的問題是「"」引號符經常會在翻譯過程中被刪掉，所以回報一下有沒有可能是與引號有關

没放弃，最近精力在其它项目上。。。

**Comment by myforself** [comment]
> > > 这个目前有些困难，因为可能无法确定哪些是代码哪些是注释，可能需要 prompt 来辅助（这样就只有 ChatGPT 才行）我们需要考虑下怎么做
> > 
> > 
> > 一個多月沒更新我還以為被放棄了…感恩還在… 順便借地問一下，有關翻譯出現格式錯誤的問題是不是目前還沒有進展…？ 我最近發現的問題是「"」引號符經常會在翻譯過程中被刪掉，所以回報一下有沒有可能是與引號有關
> 
> 没放弃，最近精力在其它项目上。。。

那就希望盡快修復這問題了…加油
