### ISSUE TITLE
You tried to access openai.ChatCompletion, but this is no longer supported in  openai>=1.0.0

### ISSUE THREAD

**Issue by liweiz** [yihong0618/bilingual_book_maker#355]
我在按照首页说明使用Docker测试时，遇到：

> You tried to access openai.ChatCompletion, but this is no longer supported in 
openai>=1.0.0 - see the README at https://github.com/openai/openai-python for 
the API.
> 
> You can run `openai migrate` to automatically upgrade your codebase to use the 
1.0.0 interface. 
> 
> Alternatively, you can pin your installation to the old version, e.g. `pip 
install openai==0.28`
> 
> A detailed migration guide is available here: 
https://github.com/openai/openai-python/discussions/742

但搜索了问题区和PR后没有看到相关解答，搜索代码可以看到确实是用openai.ChatCompletion

不知作者对此情况有何建议

谢谢

**Comment by yihong0618** [comment]
应该在本周会更新到 >1.1

**Comment by liweiz** [comment]
> 应该在本周会更新到 >1.1

多谢告知。辛苦了。

**Comment by yihong0618** [comment]
可能得下周了，有点其他事情

**Comment by liweiz** [comment]
> 可能得下周了，有点其他事情

谢谢通知。开源软件开发坚持下来不容易。我没有这个领域的开发经验，只能作为用户，而不是开发者，对贵项目表示支持。

**Comment by yihong0618** [comment]
> > 可能得下周了，有点其他事情
> 
> 谢谢通知。开源软件开发坚持下来不容易。我没有这个领域的开发经验，只能作为用户，而不是开发者，对贵项目表示支持。

感谢理解！

**Comment by yihong0618** [comment]
更新到最新了，抱歉回复慢了，你可以测一下，我先关了这个 issue 哈？欢迎随时打开
