### ISSUE TITLE
Error code: 429 will sleep 60 seconds

### ISSUE THREAD

**Issue by shxiq01** [yihong0618/bilingual_book_maker#365]
Error code: 429 will sleep 60 seconds
'str' object has no attribute 'choices' !!

429是什么错误啊？

**Comment by yihong0618** [comment]
能来个截图么
顺便分享下你的命令

**Comment by shxiq01** [comment]
> 能来个截图么 顺便分享下你的命令

<img width="393" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/12861435/1ce7bdc2-be47-428e-bfb1-8d7f6e3de097">

命令是python make_book.py --book_name D:\novel\translate\tmp\九十九次.txt --language "English" --prompt prompt_template_sample.txt  --openai_key xxxxx --api_base 'https://api.xxxx.cn/'

**Comment by shxiq01** [comment]
> > 能来个截图么 顺便分享下你的命令
> 
> <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/12861435/294448015-1ce7bdc2-be47-428e-bfb1-8d7f6e3de097.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDY3OTEsIm5iZiI6MTcwNDQ0NjQ5MSwicGF0aCI6Ii8xMjg2MTQzNS8yOTQ0NDgwMTUtMWNlN2JkYzItYmU0Ny00MjhlLWJmYjEtOGQ3ZjZlM2RlMDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5MjEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNTk0YzQ5ODBiNDQzMDBlNjEzNGRlZjk2YjE1ZTE1YzJhOGQ1YzQyZjc3ZWUyNjAyMTVjMDkzNTBhNGU4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uqRlF_YiLTbqR66EtiUBVoRN3Ne_DiPvK6Mw4jcS0qs">
> 命令是python make_book.py --book_name D:\novel\translate\tmp\九十九次.txt --language "English" --prompt prompt_template_sample.txt --openai_key xxxxx --api_base 'https://api.xxxx.cn/'

prompt是这个
<img width="781" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/12861435/d87412b9-2279-44b7-ac95-a91918ac641e">

**Comment by yihong0618** [comment]
api base 可能不对，后面应该有个 v1?

**Comment by shxiq01** [comment]
> api base 可能不对，后面应该有个 v1?

对不起老板。。我的错，忘记加了
