### ISSUE TITLE
Error code: 307

### ISSUE THREAD

**Issue by DawnLi-code** [yihong0618/bilingual_book_maker#372]
非常好的项目，感谢。反馈一下，希望能有所帮助。已经到结尾注释部分了，大不了拆分单独翻了再合并。

macOS 13.6.3，Python 3.11.4，错误提示如图，--resume也不能继续：

![截屏2024-01-21 上午12 58 41](https://github.com/yihong0618/bilingual_book_maker/assets/19859737/54eaad40-0443-4123-8e27-ff6317f1f51f)

原书：https://wwbd.lanzoul.com/idzZU1lrsz8b

**Comment by yihong0618** [comment]
谢谢我晚上看一下

**Comment by yihong0618** [comment]
@DawnLi-code 没翻译完的话也会生成一本 epub 的，到结尾的话你可以直接用那本先，我看看是什么问题

**Comment by DawnLi-code** [comment]
> @DawnLi-code 没翻译完的话也会生成一本 epub 的，到结尾的话你可以直接用那本先，我看看是什么问题

我就是把这本临时的拆分，留下没翻译的部分再跑一次翻译程序，然后合并一本。

BTW：完成的翻译文本，时不时的会夹杂几句：”请帮我把以下内容翻译成简体中文：“，“请帮我翻译成简体中文：”，“translates to `1791年至1808年` in simplified Chinese” 等等这样的句子，正在手工清理。

**Comment by yihong0618** [comment]
嗯这个是模型的原因。。。

**Comment by yihong0618** [comment]
@DawnLi-code 尝试修复了，拉一下最新代码试试？

**Comment by DawnLi-code** [comment]
辛苦，这套书还有4本，我试试有问题来反馈。

**Comment by yihong0618** [comment]
好的
