### ISSUE TITLE
这是一个什么模块，无法安装

### ISSUE THREAD

**Issue by greatany** [yihong0618/bilingual_book_maker#373]
以下是错误提示：
ModuleNotFoundError: No module named 'google.generativeai.types.generation_types'

**Comment by yihong0618** [comment]
pip install -U google-generativeai

**Comment by yihong0618** [comment]
关了哈

**Comment by Space-f-Monkey** [comment]
這八成是因為python 3.8.2無法支援，因為我也遇到相同問題
