### ISSUE TITLE
运行不报错，但是也不翻译。

### ISSUE THREAD

**Issue by yangchen859** [yihong0618/bilingual_book_maker#378]
运行 python make_book.py --book_name 1.epub --openai_key xx 命令后，直接出现这个：Using model list ['gpt-3.5-turbo-0301', 'gpt-3.5-turbo-16k', 'gpt-3.5-turbo-0613', 'gpt-3.5-turbo', 'gpt-3.5-turbo-1106', 'gpt-3.5-turbo-16k-0613']

![image](https://github.com/yihong0618/bilingual_book_maker/assets/84459277/f68aa2d9-27de-47fb-812b-82bb7e9c48dc)

**Comment by yihong0618** [comment]
参考 README 放进去其它标签。（搜索 div

**Comment by yangchen859** [comment]
> 参考 README 放进去其它标签。（搜索 div

谢谢，参考div后，成功运行了

**Comment by yangchen859** [comment]
> 参考 README 放进去其它标签。（搜索 div

现在我是用多个api,会报错。。`python make_book.py --book_name 1.epub --openai_key sk-xx,sk-xx --translate-tags div,p` , 每个单独的key多可以使用,但是合在一起就不行了.  提示我使用的api不对

**Comment by yangchen859** [comment]
![image](https://github.com/yihong0618/bilingual_book_maker/assets/84459277/33d06610-911f-4f29-b15b-e47b5d9b5fb1)

**Comment by yangchen859** [comment]
![image](https://github.com/yihong0618/bilingual_book_maker/assets/84459277/d3ff2ecf-ebb3-4c76-82fb-cf7cf7ca10af)
