### ISSUE TITLE
deepl翻译只读取，不翻译

### ISSUE THREAD

**Issue by yangchen859** [yihong0618/bilingual_book_maker#380]
这是我在rapidapi测试, 是能够翻译的
![image](https://github.com/yihong0618/bilingual_book_maker/assets/84459277/481c4afe-e5da-4bec-8c0a-cde1c89b08d3)

我使用的是这个命令, 不太确定是不是这样使用`python make_book.py --book_name test_books/animal_farm.epub --model deepl --deepl_key 5a1745ee92xxxsh16xxxxxxxxxxp1563fejsn2347d9025e6f --language ja` 这个命令时, 翻译只能读取到文本, 但是不会翻译

![image](https://github.com/yihong0618/bilingual_book_maker/assets/84459277/55e043cf-13ec-4f79-931b-77bb6832df5c)

**Comment by yangchen859** [comment]
发现问题: deepl_translator.py 中
`
        self.headers = {
            "content-type": "application/json",
            "X-RapidAPI-Key": "",
            "X-RapidAPI-Host": "deepl-translator.p.rapidapi.com",
        }
`
替换为
`
        self.headers = {
            "content-type": "application/json",
            "X-RapidAPI-Key": "",
            "X-RapidAPI-Host": "dpl-translator.p.rapidapi.com",
        }
`
就可以翻译了

**Comment by yihong0618** [comment]
> 发现问题: deepl_translator.py 中 `self.headers = { "content-type": "application/json", "X-RapidAPI-Key": "", "X-RapidAPI-Host": "deepl-translator.p.rapidapi.com", }` 替换为 `self.headers = { "content-type": "application/json", "X-RapidAPI-Key": "", "X-RapidAPI-Host": "dpl-translator.p.rapidapi.com", }` 就可以翻译了

来个 pr?

**Comment by yihong0618** [comment]
有区别，我傻逼了

**Comment by yihong0618** [comment]
@yangchen859 按照你的代码 fix 了，在 commit 里面加了感谢，谢谢你
