### ISSUE TITLE
`--resume` would raise error: `'NoneType' object has no attribute 'replace' you can resume it next time`

### ISSUE THREAD

**Issue by imWildCat** [yihong0618/bilingual_book_maker#381]
Hello, the resume functionality seems to be broken.

I tried it like
```
bbook_maker --openai_key xxx --api_base 'https://xxx.openai.azure.com/' --deployment_id 'gpt35' --book_name xxx --resume
```

it just returned 

```
'NoneType' object has no attribute 'replace'
you can resume it next time
```

there's no call stack shown

**Comment by yihong0618** [comment]
@imWildCat try to fix it, not sure if its this problem, reopen it

please try to use the latest package(or code)

**Comment by imWildCat** [comment]
thank you!

using the latest version, it now shows:

```
  0%|                                                                                | 0/4728 [00:00<?, ?it/s]









NoneType takes no arguments
you can resume it next time
```

**Comment by yihong0618** [comment]
seems something is wrong will take a look tonight or romorrow and revert the latest commit

**Comment by yihong0618** [comment]
@imWildCat seems fixed this time

**Comment by imWildCat** [comment]
I can confirm the fix. thanks for your quick action!
