### ISSUE TITLE
翻译 epub, 使用 --resume 以后格式出现问题

### ISSUE THREAD

**Issue by STRRL** [yihong0618/bilingual_book_maker#386]
temp 文件中的格式是正确的:
![image](https://github.com/yihong0618/bilingual_book_maker/assets/20221408/b7da4e21-a447-4eb8-a63b-5ce039308b55)

使用 resume 后, 最终的输出格式错误:

![image](https://github.com/yihong0618/bilingual_book_maker/assets/20221408/88ffeb70-e0b9-4d32-b7d5-356d82871393)

目前表现是:

- 英文原文丢失
- 中英文段落位置调换(先中文后英文)

**Comment by yihong0618** [comment]
Fixed

**Comment by MrGuin** [comment]
这个问题仍然存在，翻译了三本书全部都是这样
