### ISSUE TITLE
Feature Request: support for Groq mixtral-8x7b-32768

### ISSUE THREAD

**Issue by saccohuo** [yihong0618/bilingual_book_maker#388]
Groq API is compatible with openai, so could you add a --model option for mixtral-8x7b-32768 in Groq?
Thanks.

**Comment by yihong0618** [comment]
sounds great and PR welcome.
I will take a look later, if no one want to open a PR to support

**Comment by yihong0618** [comment]
@saccohuo it can use  now 
check https://github.com/yihong0618/bilingual_book_maker/pull/392
