### ISSUE TITLE
GPT-4 Models have large differences in price

### ISSUE THREAD

**Issue by TimelyToga** [yihong0618/bilingual_book_maker#390]
I think that we should allow some further customization of which models that a user actually wants to use when translating, because the regular `gpt-4` model is *significantly* more expensive than the turbo versions of the same models. 

But all of these models are grouped together as choices to pull from when translating content. I ran a short test of 75 paragraphs and the price disparity is pretty shocking:

<img width="352" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/5962178/e9d3bd36-cdbc-431b-b7ed-f784492c9ab0">

### Vanilla `gpt4`
<img width="859" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/5962178/515cc185-eb1c-4c5a-a3fd-f7e7e53cab3d">

### Turbo `gpt4`
<img width="857" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/5962178/50686413-3d51-4e5d-a0f2-88ea3a6e62ea">

### Proposed solution 
I think that it would be a good idea to expose `gpt4-turbo` as well as `all-gpt4` as model options and include some documentation that explains this, because if I wasn't paying attention I could have accidentally significantly overpaid. 

Another option would be just to remove vanilla `gpt-4` by default since the turbo models have incredibly high limits on even level 1 accounts now: 

<img width="745" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/5962178/762b8846-9df1-45ed-9efd-6ee02bc19f9b">

I'm open to discussing better options here, but I do think that at the very least some documentation updates should be made to make it clear that both turbo and regular models are grouped together like this. Happy to hop in and help if there is some consensus on a good structure for this. 

I would just hop in and write the code, but probably worth some discussion since this would involve some changes to the external API.

**Comment by yihong0618** [comment]
yes you are right we can fix one specific model, PR welcome for that.

Thank you very much

**Comment by TimelyToga** [comment]
Perfect. I will take a look at adding this code tonight.

**Comment by TimelyToga** [comment]
Resolved with that merge
