### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by changchiyou** [yihong0618/bilingual_book_maker#394]
大部分時候翻譯正常、只會偶爾噴錯：

<img width="1440" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/46549482/342f1f45-72c3-441a-aeda-bc0b52070245">

但有時會無限噴錯，一直`--resume`也沒用：

<img width="1440" alt="image" src="https://github.com/yihong0618/bilingual_book_maker/assets/46549482/01c12766-f497-40c8-85ce-d3627ac52603">

**Comment by yihong0618** [comment]
这个报错是你用了 free chatgpt-3.5 报的错。。

**Comment by yihong0618** [comment]
> 这个报错是你用了 free chatgpt-3.5 报的错。。

我之后完善下报错信息，抱歉最近精力没在这上

**Comment by changchiyou** [comment]
是我使用的 gpt 出問題了，我這邊再自己研究下
