### ISSUE TITLE
feat 支持多个 token 用逗号分隔

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/bilingual_book_maker#4]
来摆脱 limit 限制。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by yihong0618** [comment]
谁有兴趣 PR welcome

**Comment by guaguaguaxia** [comment]
我来我来，今晚或者周末写

**Comment by guaguaguaxia** [comment]
https://github.com/yihong0618/bilingual_book_maker/pull/14

**Comment by yihong0618** [comment]
Done
