### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by NielloNiello** [yihong0618/bilingual_book_maker#400]
您好，按教程安装了python-3.12.3-macos11，pip install -r requirements.txt

运行test code的时候一直出现connection报错。

Connection error.
NoneType takes no arguments
you can resume it next time

附上log，能否麻烦您解答🙏

[Terminal Saved Output.txt](https://github.com/yihong0618/bilingual_book_maker/files/15314727/Terminal.Saved.Output.txt)

**Comment by NielloNiello** [comment]
您好！用最新release尝试，成功了
[v0.7.0 release](https://github.com/yihong0618/bilingual_book_maker/releases/tag/v0.7.0)

**Comment by yihong0618** [comment]
好的
