### ISSUE TITLE
[Feature Request] Support OpenAI's Batch API

### ISSUE THREAD

**Issue by vizmoe** [yihong0618/bilingual_book_maker#401]
According to [OpenAI](https://platform.openai.com/docs/guides/batch), the Batch OpenAI API can save up to 50% of API call costs and is suitable for processing non-real-time data. Currently, translating documents could consume a large amount of API credits. Supporting the Batch API would significantly reduce users' costs.

**Comment by yihong0618** [comment]
will take a look
and PR welcome~

**Comment by mkXultra** [comment]
@yihong0618 @vizmoe 
I'm working on it. its almost done.
https://github.com/yihong0618/bilingual_book_maker/pull/423

**Comment by mkXultra** [comment]
@yihong0618 
I'm done. plz review it if you have time.
