### ISSUE TITLE
Gemini連續429錯誤

### ISSUE THREAD

**Issue by Space-f-Monkey** [yihong0618/bilingual_book_maker#406]
錯誤訊息如下：
429 Resource has been exhausted (e.g. check quota).
Can not translate by other reason.(因安全问题不能翻译)

我試過使用數個API keys，但不論我用哪種方式（像加上${,}或(,)或直接加,），
系統都只會傳400錯誤（API keys無效）。

Gemini好像可以用延遲來改善429錯誤，
但我不確定這段python要插入哪裡才好。以下是Google說延遲可用的程式碼：
https://developers.google.com/google-ads/api/samples/handle-rate-exceeded-error?hl=zh-tw#python

**Comment by yihong0618** [comment]
我研究下，谢谢

**Comment by jojogh** [comment]
Can not translate by other reason.(因安全问题不能翻译)
这个信息似乎是个bug，我翻译某些文档也遇到过这个错误，我看看能否修复这个bug。

**Comment by jojogh** [comment]
![image](https://github.com/yihong0618/bilingual_book_maker/assets/142501/85f3c84a-723b-41e1-ac17-3bde1f87d1b1)
换了一个Gemini 付费的key，现在似乎没有报“Can not translate by other reason.(因安全问题不能翻译)”信息。

**Comment by Space-f-Monkey** [comment]
我現在就是用付費版，問題應該真的是延遲與否，因為就算是付費，只要翻譯的句太短、太多句子太短，就會達到請求的上限。

之前我翻譯的書本比較古老，每一段都很長，所以沒這問題。
麻煩的是，較近代的書本分段很隨意，而只要有一次429錯誤，就會連續429多次，直到我的網路稍微延遲一陣子。

**Comment by yihong0618** [comment]
应该是 gemini 需要付费的问题（得换 key 否则会频繁 limit 我之后研究下

**Comment by jojogh** [comment]
找了几本书，连续用Gemini付费接口测试翻译，均没有报429错误。

**Comment by Space-f-Monkey** [comment]
> 找了几本书，连续用Gemini付费接口测试翻译，均没有报429错误。

今天試了下，還是一樣容易連續跳出429。或許這是我的網路的問題。
如果yihong大研究過後，決定不改，那我可以改用其他我目前能跑的API⋯⋯
就算騰訊有時候愛翻不翻，還會跳出不相關的色情小說橋段，
但至少騰訊還堪用，不會連續跳出錯誤。

**Comment by Space-f-Monkey** [comment]
忘了說。
我目前在翻的是Wildbow 的Pale，差不多在0.0章節第六十段的時候會開始連續出錯。

**Comment by jojogh** [comment]
大概多少文字你这本书？如果书分章节，可以分章节翻译

**Comment by yihong0618** [comment]
> 忘了說。 我目前在翻的是Wildbow 的Pale，差不多在0.0章節第六十段的時候會開始連續出錯。

感觉还像 limit 问题，我一会儿把 base model 换成 flash

**Comment by abdurahmanadilovic** [comment]
how the rate-limiting works in generals, if I try to use the Gemini flash 1.5 which is free, and I have a certain amount of requests per minute and per day, how easy is it to implement those restrictions?

**Comment by taiwanKiddo** [comment]
import google.generativeai as genai
import json
import os
import sys

class GeniAIException(Exception):
    " "

class chatBot:
    chatBot_name = "bot"

    def __init__(self, api_key, history_file_path):
        self.genai = genai
        self.genai.configure(api_key=api_key)
        self.model = self.genai.GenerativeModel('gemini-pro')
        self.history_file_path = history_file_path
        self._conversation_history = []
        self.load_history()
        self.start_conversation()

    def send_prompt(self, prompt, temperature=0.5):
        if temperature < 0 or temperature > 1:
            raise GeniAIException("Temperature must be between 0 and 1.")
        if not prompt:
            raise GeniAIException("Prompt cannot be empty.")

        try:
            response = self.conversation.send_message(
                content={"text": prompt},  # Ensure content is a simple dictionary with text
                generation_config=self._generation_config(temperature)
            )
            response.resolve()

            if response.text:
                response_text = response.text.strip()
                self._update_history(prompt, response_text)
                self.save_history()
                return response_text + '\n' + '---' * 20
            else:
                raise GeniAIException("Received an empty response from the API.")
                
        except Exception as e:
            print(f"Error handling response: {str(e)}")
            return "An error occurred, please try again."

    def load_history(self):
        if os.path.exists(self.history_file_path):
            with open(self.history_file_path, 'r') as file:
                # Ensure the loaded history is a list of dicts with {"text": "<message>"} format
                self._conversation_history = json.load(file)
        else:
            self._conversation_history = []

    def save_history(self):
        with open(self.history_file_path, 'w') as file:
            json.dump(self._conversation_history, file, indent=4)

    def _update_history(self, user_message, bot_message):
        # Store history as expected by the API, using dict format for messages
        self._conversation_history.append({"text": user_message})
        self._conversation_history.append({"text": bot_message})

    def start_conversation(self):
        """Initialize conversation and set up initial chat history if applicable."""
        self.conversation = self.model.start_chat()
        # Apply history only if it's in the correct format for the API
        if self._conversation_history:
            for part in self._conversation_history:
                if isinstance(part, dict) and "text" in part:
                    self.conversation.send_message(content=part)  # Ensure each message is a dictionary with "text" key

    def _generation_config(self, temperature):
        return genai.types.GenerationConfig(
            temperature=temperature
        )
,試試看

**Comment by colin4k** [comment]
> 把gemini_translator.py中time.sleep修改成1秒或者3秒试试？
> 
> `time.sleep(1.0) if num: t_text = str(num) + "\n" + t_text return t_text`

改成 3s 有效

**Comment by yihong0618** [comment]
Changed to sleep 3
