### ISSUE TITLE
Single-language book format (not bilingual)

### ISSUE THREAD

**Issue by gcharycki** [yihong0618/bilingual_book_maker#409]
I would like to translate an EPUB file, for example, from English to French, but I do not want the new file to have the text repeated twice; I want it to appear only once (in French). I would like every word to be in French, not just the content, but also the book title, chapters, etc. How can I achieve this? Unfortunately, I cannot find the required option.

**Comment by HadesNinth** [comment]
use --single_translate

**Comment by mkXultra** [comment]
I've update readme
https://github.com/yihong0618/bilingual_book_maker/pull/421
