### ISSUE TITLE
·pip install -r requirements.txt· 安装完后使用还是会有各种 ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by h9nara** [yihong0618/bilingual_book_maker#413]
`pip install -r requirements.txt` 安装完后，使用时还是报错各种 ModuleNotFoundError: No module named 'openai'
然后我每 pip3 install $package_name_1 --break-system-packages 完后才会pass当前的ModuleNotFound然后遇到下一个ModuleNotFound

不熟悉python env 不知道应该会安装命令做那些改动

**Comment by yihong0618** [comment]
python3 -m pip install -r requirements.txt

**Comment by h9nara** [comment]
感谢您这么及时的回复，我用
python3 -m pip install -r requirements.txt --break-system-packages
然后能用了

**Comment by yihong0618** [comment]
好的
