### ISSUE TITLE
GPT-4o Mini Support + Update Tokenizer

### ISSUE THREAD

**Issue by HadesNinth** [yihong0618/bilingual_book_maker#416]
GPT-4o Mini is significantly cheaper and more quality than GPT-3.5.

GPT-4o Mini seems to be a bit slower than GPT-3.5-turbo, but latency really only matters for chatbot. For translation purposes, I suggest we just straight up replace 3.5 options with 4o Mini as the default.

I'm told it also uses the GPT-4o uses the o200k_base tokenizer, different from GPT-4 models. So probably update that as well.

**Comment by yihong0618** [comment]
will update this week, thanks

**Comment by mkXultra** [comment]
@yihong0618 
I implemented support gpt4o-mini model.
plz check this PR #419

**Comment by yihong0618** [comment]
Done
