### ISSUE TITLE
输入翻译命令后 没有进行任何翻译就完成了

### ISSUE THREAD

**Issue by h9nara** [yihong0618/bilingual_book_maker#417]
我的命令行：
```
[I] ➜ python3 make_book.py --book_name test_books/amazon_behaviroal.epub  --model google
0it [00:00, ?it/s]
0it [00:00, ?it/s]
bilingual_book_maker on  main [!?] took 2s
```
我看到有_bilingual后缀的书籍生成，但是没有走进度条，命令直接执行完了，不知道是什么情况，我之前有成功翻译别的书籍。
不知道有没有verbose logging模式？

**Comment by yihong0618** [comment]
> 我的命令行：
> 
> ```
> [I] ➜ python3 make_book.py --book_name test_books/amazon_behaviroal.epub  --model google
> 0it [00:00, ?it/s]
> 0it [00:00, ?it/s]
> bilingual_book_maker on  main [!?] took 2s
> ```
> 
> 我看到有_bilingual后缀的书籍生成，但是没有走进度条，命令直接执行完了，不知道是什么情况，我之前有成功翻译别的书籍。 不知道有没有verbose logging模式？

可能你那本书没有 p 标签，参考 README 把 div 啥的放进去

**Comment by h9nara** [comment]
加了各种tag后确实就运行正常了，感谢
