### ISSUE TITLE
如何对api url进行替换？

### ISSUE THREAD

**Issue by Tongzhao9417** [yihong0618/bilingual_book_maker#42]
由于网络问题，我只能使用cf的路由来转发api的地址，具体方法参考如下讨论
https://github.com/noobnooc/noobnooc/discussions/9#discussion-4925163

在申请好自己的url之后，本想着对Python文件里的URL进行替换，但是发现只有GPT3的可以，chatGPT的不能替换。请问可以增加一下吗？

**Comment by yihong0618** [comment]
let me try.

**Comment by yihong0618** [comment]
更新了，但我手头没法测试
@Tongzhao9417 试试 --api_base ${url}

**Comment by Tongzhao9417** [comment]
> 更新了，但我手头没法测试 @Tongzhao9417 试试 --api_base ${url}

可是使用了，感谢！（ps，可以在说明文档里标注一下，api的URL是要包含"v1"的嘛，现在很多插件在涉及到URL替换时标准都不一样，谢谢了！）

**Comment by yihong0618** [comment]
你有兴趣提个 PR 么？帮忙修复一下文档，包括 README  和 README-CN

**Comment by Tongzhao9417** [comment]
> 你有兴趣提个 PR 么？帮忙修复一下文档，包括 README 和 README-CN

荣幸至极（忘了更新英文版的readme，现在去改）

**Comment by yihong0618** [comment]
@依然没改 README 啊，改了两次 cn

**Comment by Tongzhao9417** [comment]
> @依然没改 README 啊，改了两次 cn

已修改

**Comment by yihong0618** [comment]
关了哈
