### ISSUE TITLE
有没有人能教一下到底Grop要怎用

### ISSUE THREAD

**Issue by myforself** [yihong0618/bilingual_book_maker#427]
指令 python make_book.py -model groq --model_list llama3-8b-8192 --groq_key [my key] --book_name [bookname] --language zh-hans

直接跳指令出来说没groq

**Comment by yihong0618** [comment]
我看看之后回你

**Comment by umm233** [comment]
> 指令 python make_book.py -model groq --model_list llama3-8b-8192 --groq_key [my key] --book_name [bookname] --language zh-hans
> 
> 直接跳指令出来说没groq

You can try this: 

```
python3 make_book.py --book_name test_books/animal_farm.epub --groq_key [your_key] --model groq --model_list groq
```

**Comment by yihong0618** [comment]
@umm233 thanks
