### ISSUE TITLE
要是有个progress bar就好啦

### ISSUE THREAD

**Issue by riverscn** [yihong0618/bilingual_book_maker#5]
如题

**Comment by yihong0618** [comment]
代码里有这个的 todo 哈哈，之后会用 tqdm 加上

**Comment by yihong0618** [comment]
TODO

- [x] count all the p
- [ ]  bring `tqdm`
- [ ] count the index -> show to the process bar
- [ ] when --resume go to the process bar index first

**Comment by yihong0618** [comment]
Done
