### ISSUE TITLE
指定gpt3但是好像依然使用旧的模型

### ISSUE THREAD

**Issue by pzcn** [yihong0618/bilingual_book_maker#55]
![image](https://user-images.githubusercontent.com/29601158/222972513-b95f6b34-2389-462b-afbd-dad743695da1.png)
我看了下确实指定了gpt3，但是看openai官方的扣费情况还是达芬奇，请问问题可能出在哪里呢
![image](https://user-images.githubusercontent.com/29601158/222972594-9de5da7f-5774-4e9e-9bfa-6a29a888e8a8.png)

**Comment by tianshanghong** [comment]
`gpt3`即是`text-davinci-003`，`chatgpt`才是`chatgpt`。 `--model`不指定的话默认就是 `chatgpt`. 
https://github.com/yihong0618/bilingual_book_maker/blob/main/make_book.py#L266-L268

**Comment by pzcn** [comment]
> `gpt3`是`text-davinci-003`，`chatgpt`才是`chatgpt`。 `--model`不指定的话默认就是 `chatgpt`. https://github.com/yihong0618/bilingual_book_maker/blob/main/make_book.py#L266-L268

那请问gpt-3.5-tubor是选择“chatgpt”吗

**Comment by tianshanghong** [comment]
是。或者不指定，默认就是gpt-3.5-tubor

**Comment by pzcn** [comment]
明白了，谢谢
