### ISSUE TITLE
编码解码器无法编码，序数不在范围内

### ISSUE THREAD

**Issue by yanedie** [yihong0618/bilingual_book_maker#57]
扔了一个18M的epub文件，标题还没开始翻译，就报了这些出来，然后就停止了。
'latin-1' codec can't encode character '\uff0c' in position 58: ordinal not in range(256) will sleep  60 seconds
'latin-1' codec can't encode character '\uff0c' in position 58: ordinal not in range(256)
you can resume it next time

**Comment by InzamZ** [comment]
方便提供epub文件吗？我在尝试修复

**Comment by InzamZ** [comment]
已经合并，你再试一试？ @yanedie

**Comment by yanedie** [comment]
> 已经合并，你再试一试？ @yanedie
现在报错内容是这样的（是不是因为网络原因？有梯子）：
HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
) will sleep  30 seconds
Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code':
'internal_error'}} {'Date': 'Tue, 07 Mar 2023 12:08:35 GMT', 'Content-Type': 'application/json; charset=utf-8',
'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id':
'cd164570d44b20692a3e80d8b54506e1', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}

---
以下是我用的电子书文件：
dita.epub
https://www.aliyundrive.com/s/DYaSF4g16Hd
提取码: 78me
---
辛苦了。

**Comment by InzamZ** [comment]
![image](https://user-images.githubusercontent.com/73429001/223420514-04641256-77cb-498e-883a-0f00b684117c.png)

应该没有问题了 ，你再试试@yanedie

**Comment by InzamZ** [comment]
![image](https://user-images.githubusercontent.com/73429001/223420514-04641256-77cb-498e-883a-0f00b684117c.png)

应该没有问题了 ，你再试试@yanedie

**Comment by yanedie** [comment]
> ![image](https://user-images.githubusercontent.com/73429001/223420514-04641256-77cb-498e-883a-0f00b684117c.png)
> 
> 应该没有问题了 ，你再试试@yanedie

没有问题，可以了，非常感谢。

**Comment by myjeshurun** [comment]
我碰到了同样的问题，使用的是你提供test_books里面的文件，每个都不行。一样的报错：'latin-1' codec can't encode character '\uff0c' in position 58: ordinal not in range(256) will sleep 60 seconds
'latin-1' codec can't encode character '\uff0c' in position 58: ordinal not in range(256)
3次之后说：
Get 3 consecutive exceptions
'latin-1' codec can't encode character '\u201c' in position 7: ordinal not in range(256)
Something is wrong when translate
you can resume it next time
