### ISSUE TITLE
要是能有断点继续功能就好啦

### ISSUE THREAD

**Issue by riverscn** [yihong0618/bilingual_book_maker#6]
如题

**Comment by yihong0618** [comment]
TODO

- [ ] when next try failed -> catch error
- [ ] add p_t translate list -> append every time
- [ ] when failed or CTRL+C go then `pickle` the list -> to the same name file like `.temp.animal_farm.bin`
- [ ] add command --resume  when `--resume` load the bin -> do not call the translate -> to the index
- [ ] gogogo

**Comment by yihong0618** [comment]
支持了
