### ISSUE TITLE
这个开源项目可能涉及的版权问题

### ISSUE THREAD

**Issue by lextm** [yihong0618/bilingual_book_maker#60]
这个开源项目选择基于 MIT 开源许可证发布代码，那么我想作者至少对于版权、开源有初步的了解和认识。开源运动首先尊重代码作者的版权，并基于对应的开源许可证来指导对于版权保护下代码的合理使用。

那么这个项目目前被使用的情况就不免让人有疑问。它的广大用户群体正在翻译的材料版权状况是怎样的？毕竟除非因为版权失效而进入公域，书籍、论文的原始作者、出版机构是持有版权或授权的，并有权享受原创内容带来的权益，这也是为了保证原创内容不断发展壮大。

这个项目翻译后的内容被如何使用和传播？翻译后的内容的传播如果侵犯了版权所有者的权益，是否会回溯到这个开源项目本身？#24 的讨论已经触及到了问题。那么不加以延伸讨论，而是提前关闭它，就不是一个好办法。

附上 Bing Chat 的一些提示
![image](https://user-images.githubusercontent.com/425130/222981695-27f26ed5-b65c-465c-809d-8ab1bc5d1723.png)

**Comment by yihong0618** [comment]
谢谢，提醒。这是个工具，不会提供版权的书，放进去的 test_book 是进入公共领域的书。
它不会主动去传播侵权的内容，前辈对于如何讨论有什么建议么？我把 #24 打开了，谢谢你

**Comment by yihong0618** [comment]
另外这个 issue 我之后会关掉，我开了 discuss 我觉得这种问题放在 discuss 里讨论更好一些

**Comment by yihong0618** [comment]
https://github.com/yihong0618/bilingual_book_maker/discussions
