### ISSUE TITLE
最后生成新epub文件时提示ERROR:root:Could not create metadata "user_metadata:#id".

### ISSUE THREAD

**Issue by 141238** [yihong0618/bilingual_book_maker#65]
最后生成新epub文件时提示ERROR:root:Could not create metadata "user_metadata:#id"导致没有新文件生成，请问这个是什么原因呢
![image](https://user-images.githubusercontent.com/127076407/223024495-560ec636-c4a2-4503-873a-28fe4489c74d.png)

**Comment by yihong0618** [comment]
没关系，已经生成了

**Comment by 141238** [comment]
喔，刷新看到了，感谢

**Comment by 141238** [comment]
![image](https://user-images.githubusercontent.com/127076407/223031829-f37ed4ed-9319-4e11-b835-613eb5daa787.png)
这种在中间停住不动几分钟都没有反应了，是什么原因呢，是正常情况么，如何解决呢

**Comment by yihong0618** [comment]
sleep 60 因为 limit

**Comment by tonytao0** [comment]
请问这个问题最后怎么解决的呢？  我也出现了

**Comment by yihong0618** [comment]
> 请问这个问题最后怎么解决的呢？ 我也出现了

理论上能正常生成
