### ISSUE TITLE
提供一個 txt 引擎

### ISSUE THREAD

**Issue by DennySORA** [yihong0618/bilingual_book_maker#68]
我這邊提供一個，處理 txt 的引擎，我測試過後十分的完美，能夠處理上下文 token 的總數，還會將內容作整理跟格式化。

https://gist.github.com/DennySORA/ee05480e529f23b401bcbb0a81454a22

**Comment by yihong0618** [comment]
感谢～

**Comment by DennySORA** [comment]
我這邊還發現有時候翻溢出來還是原文。

因此加入了檢查機制，最多可重來5次。

**Comment by yihong0618** [comment]
done some refactor, and will add txt_loader.
