### ISSUE TITLE
【建议】可自行设置 Prompt，基于不同类型的书籍用不同风格的语言进行翻译

### ISSUE THREAD

**Issue by 7enChan** [yihong0618/bilingual_book_maker#72]
如题，希望在翻译之前可以自行配置 Prompt，这样不同类型的书可以用不同的风格进行翻译。

**Comment by yihong0618** [comment]
@7enChan #https://github.com/yihong0618/bilingual_book_maker/pull/56

**Comment by yihong0618** [comment]
Done
