### ISSUE TITLE
【建议】增加对epub书籍章节的选择

### ISSUE THREAD

**Issue by Tongzhao9417** [yihong0618/bilingual_book_maker#73]
今天在翻译一本书的时候发现，往往书籍的最后都是参考文献，或脚注内容的解释，抑或是专业术语的索引表。如果把这些内容都加入翻译的队列里，不仅浪费token，也会因为过于频繁的request而导致任务停止。因此如果可以选择忽略哪些章节不去翻译，可能效果会更好~

**Comment by yihong0618** [comment]
好像可行。

**Comment by Tongzhao9417** [comment]
> 好像可行。

可能逻辑上会复杂一些？有的书排版比较差劲，无法识别出里面的chapter信息

**Comment by yihong0618** [comment]
是的

**Comment by Tongzhao9417** [comment]
> 是的

或者换一个思路，我们可以在他翻译到附录部分的时候，手动打断，然后直接输入生成epub的代码

比如程序跑到了翻译附录这里，经常因为request太多而被自动停止。但是由于还没有翻译完，所以我输入了resume之后会继续翻译。如果我能用什么指令来终止翻译，进入生成epub这一步，这个问题是不是就解决了？

**Comment by yihong0618** [comment]
可以的。我想想。

**Comment by Tongzhao9417** [comment]
> 可以的。我想想。

我土法制炮了一下，直接在他暂停了一次后，把没有翻译的部分都删掉了:)现在已经翻译完了

**Comment by yihong0618** [comment]
可以，我现在有思路了，晚上弄吧。。。

**Comment by yihong0618** [comment]
@Tongzhao9417 
做完了，会生成个临时的 `animal_farm_bilingual_temp.epub` temp book 
你后面的不想翻译了直接改名就行
