### ISSUE TITLE
如何限制翻译页码？

### ISSUE THREAD

**Issue by ivan509-hub** [yihong0618/bilingual_book_maker#76]
想问问，1/ 如果一个epub的电子书，太多页数了，怎么限制所翻译的页码？

2/ 怎么手动暂停翻译呀？暂定后可以导出已经翻译好的吗？

3/ 之后怎么从上次中断的地方继续翻译下去？

我之前试过问ChatGPT这些问题，感觉它给出的方案解决不了（或者我操作不当，所以才来issue）

**Comment by yihong0618** [comment]
same as #73

**Comment by yihong0618** [comment]
1,2 目前不行，我稍后支持
3 --resume

**Comment by yihong0618** [comment]
增加了

**Comment by ivan509-hub** [comment]
> 2/ 怎么手动暂停翻译呀？暂定后可以导出已经翻译好的吗？

谢谢回复～
