### ISSUE TITLE
运行后并没有提问，生成的和原文件一致（附带截图和epub文件）

### ISSUE THREAD

**Issue by 141238** [yihong0618/bilingual_book_maker#92]
运行后并没有提问，生成的和原文件一致
直接生成文件：
![image](https://user-images.githubusercontent.com/127076407/223405603-92f090e0-316e-4962-b0e3-6c33cfa8a460.png)
正常的：
![image](https://user-images.githubusercontent.com/127076407/223405853-19d8c7c5-5357-4e11-95f2-129777bc039b.png)
文件：
[ChrisAlle.zip](https://github.com/yihong0618/bilingual_book_maker/files/10908705/ChrisAlle.zip)

**Comment by yihong0618** [comment]
OK 我们之后看一下

**Comment by InzamZ** [comment]
我确实发现了一种可以实现的方法，通过改变一个参数实现

实现起来很简单，但是没有标签包括的文本可能存在一定风险，我先在本地测试一下
