### ISSUE TITLE
有想过增加彩云小译api的支持嘛

### ISSUE THREAD

**Issue by yongqiangning** [yihong0618/bilingual_book_maker#93]
我对比了彩云小译和chatgpt的翻译结果，发现彩云小译的翻译更加的流畅，建议支持彩云小译的api，或者我听说chat gpt也能够设置口语化的程度,建议开放这个参数

**Comment by yihong0618** [comment]
可以加。哈哈。
另外 PR welcome

**Comment by yihong0618** [comment]
@yongqiangning 支持了 感谢 @Voyageyang

**Comment by Voyageyang** [comment]
> @yongqiangning 支持了 感谢 @Voyageyang
我突然发现README里面command的--openai_key那里我忘改了，要改成--caiyun_key，你有时间的话要不要改一下
