### ISSUE TITLE
请教一下，为啥显示 no module named openai

### ISSUE THREAD

**Issue by wuqinqiang** [yihong0618/bilingual_book_maker#94]
![截屏2023-03-07 20 16 06](https://user-images.githubusercontent.com/36129334/223419817-42eb8856-d347-4c04-9128-807defd8c369.png)

**Comment by yihong0618** [comment]
pip install openai

**Comment by wuqinqiang** [comment]
原来是我本地python多版本冲突了，使用 python3 看版本的是3.10.8,下载依赖pip的时候又是3.9版本，导致执行程序的时候python3.10.8没有相关依赖，已解决，感觉老哥，好东西👍
