### ISSUE TITLE
Close tag - doesn't match any open tag

### ISSUE THREAD

**Issue by ChyiYaqing** [yihong0618/bilingual_book_maker#96]
运行指令: 
`➜ python3 make_book.py --book_name ~/name.epub --openai_key <openai_key> --language "Simplified Chinese"
`

运行结果: 
```
请帮我翻译" )"成简体中文，只需返回翻译后的内容，不包括原文。
func main() {
Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) will sleep  60 seconds


主函数() {
. . .


请帮我翻译`. . .`为简体中文，只回复翻译后的内容，不包括原文。
closing tag '[/*key*/ string, /*value*/ int]' at position 13 doesn't match any open tag
you can resume it next time
16502it [15:49:35,  3.45s/it]
```

运行意外中止，请问这里是什么原因导致？

**Comment by yihong0618** [comment]
> Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) will sleep  60 seconds

看起来是网络问题

**Comment by ChyiYaqing** [comment]
多谢，确实部署环境的VPS-Bandwagon网络访问OpenAI不稳定。
但是这里程序处理网络异常有尝试重新与OpenAI建立连接，这个错误`doesn't match any open tag`应该属于openai  库create的异常错误。不是很清楚这里的open tag具体含义
